### ISSUE TITLE
Choose path for ingress

### ISSUE THREAD

**Issue by quentinalbertone** [skupperproject/skupper#1026]
hello,

I would like to deploy several skupper behind a nginx ingress manager on kubernetes.
I'm checking the code and I can see that all the ingress created by skupper-site have the same path
https://github.com/skupperproject/skupper/blob/1.2/pkg/kube/ingress.go#L50
Is there a way to change this path ?

thanks

**Comment by grs** [comment]
The ingresses created by skupper set namespace specific hosts. You can have multiple skupper installations in different namespaces and the ingress controller should manage the traffic to the right instance. It does so using host though, not path.

**Comment by quentinalbertone** [comment]
Sorry, I did not explain my problem well: I would like to deploy several skupper behind the same nginx and route the traffic thanks to the path of the url.
ex:
`my.domain.com/skupper1` -> `skupper1` in namespace `foo`
`my.domain.com/skupper2` -> `skupper2` in namespace `bar`

**Comment by grs** [comment]
We can't do that because the protocol involved is not http. That is why we use the host domain. eg.

```
foo.my.domain.com -> skupper1 in namespace foo
bar.my.domain.com -> skupper2 in namespace bar
```

**Comment by quentinalbertone** [comment]
aaaah ok thanks !
