### ISSUE TITLE
skupper.io/url of token is incorrect when using ingress

### ISSUE THREAD

**Issue by aii-nozomu-oki** [skupperproject/skupper#1072]
# Skupper version

1.3.0

# How to reproduce

## Install K3s

```bash
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.26.1+k3s1" sh -s -

sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
```

## Install Skupper CLI

```bash
curl https://skupper.io/install.sh | sh
```

## Deploy site-controller

```bash
kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/1.3.0/cmd/site-controller/deploy-watch-current-ns.yaml
```

## Create skupper-site configmap
```
apiVersion: v1
data:
  console: "true"
  console-authentication: internal
  console-ingress: nodeport
  console-password: ""
  console-user: ""
  ingress: ingress
  ingress-annotations: kubernetes.io/ingress.class=traefik
  ingress-host: test.com
  name: default
  router-console: "false"
  router-logging: ""
  router-mode: interior
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
  namespace: default
```

An ingress like this is created:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: "2023-03-28T08:23:22Z"
  generation: 1
  name: skupper
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: e2376b0e-8486-46ec-8210-dfba682b4046
  resourceVersion: "946"
  uid: 94685b8f-cbfe-4148-879e-21326f2ca5d3
spec:
  ingressClassName: traefik
  rules:
  - host: claims.default.test.com
    http:
      paths:
      - backend:
          service:
            name: skupper
            port:
              number: 8081
        path: /
        pathType: Prefix
  - host: inter-router.default.test.com
    http:
      paths:
      - backend:
          service:
            name: skupper-router
            port:
              number: 55671
        path: /
        pathType: Prefix
  - host: edge.default.test.com
    http:
      paths:
      - backend:
          service:
            name: skupper-router
            port:
              number: 45671
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.128.0.41
```

`skupper token create` will create the following token

```
apiVersion: v1
data:
  ca.crt: [ca.crt]
  password: [password]
kind: Secret
metadata:
  annotations:
    skupper.io/generated-by: e2376b0e-8486-46ec-8210-dfba682b4046
    skupper.io/site-version: 1.3.0
    skupper.io/url: https://test.com:32640/06916f46-cd42-11ed-86d3-42010a800029
  creationTimestamp: null
  labels:
    skupper.io/type: token-claim
  name: 06916f46-cd42-11ed-86d3-42010a800029
```

Probably `skupper.io/url` should be https://claims.default.test.com:...

# Reason

Ingress information is retrieved after other service types.
https://github.com/skupperproject/skupper/blob/1.3.0/client/token_claim_create.go#L151-L166
In this case, `cli.getControllerIngressHost()` is executed assuming the service type is NodePort.

**Comment by grs** [comment]
The reason this happens is the setting `console-ingress: nodeport`, which causes the `skupper` service to be created as a node port service. When determining the url, it looks at that service and based on the type assumes it can be reached through the ingress host and a node-port. This assumes that the value of ingress-host will route to one of the nodes in the cluster.

Can I ask if there is a specific need for the console-ingress to be node-port when using ingress as the value for the general ingress?

**Comment by ohkinozomu** [comment]
Thanks, by `console-ingress: ingress` or `console-ingress: none` or `console: "false"`, skupper.io/url is like `https://claims.default.test.com:443/efd8cf3e-cdc3-11ed-abc9-42010a800029`.

> Can I ask if there is a specific need for the console-ingress to be node-port when using ingress as the value for the general ingress?

No special reason.
I’m in the process of trying Skupper and tried to avoid the security risk of exposing the console.

I think it is a good idea to raise a warning or validation error about the combination of `console-ingress: nodeport` and `ingress: ingress`, what do you think?

**Comment by aii-nozomu-oki** [comment]
Thanks, by console-ingress: ingress or console-ingress: none or console: "false", skupper.io/url is like https://claims.default.test.com:443/efd8cf3e-cdc3-11ed-abc9-42010a800029.

Can I ask if there is a specific need for the console-ingress to be node-port when using ingress as the value for the general ingress?

No special reason.
I’m in the process of trying Skupper and tried to avoid the security risk of exposing the console.

I think it is a good idea to raise a warning or validation error about the combination of console-ingress: nodeport and ingress: ingress, what do you think?

**Comment by grs** [comment]
> I think it is a good idea to raise a warning or validation error about the combination of `console-ingress: nodeport` and `ingress: ingress`, what do you think?

I certainly agree that the current behaviour is confusing. The root of the issue is that claim tokens are redeemed for certificates using the skupper service instead of the skupper-router service. We could fix the current logic you referenced to handle this case. Or we could warn as you say. Ultimately I would like to move the handling of the claims to avoid the confusion entirely. Let me think it over a bit as to what the short term approach should be.

Thanks for your excellent feedback!
