### ISSUE TITLE
cannot assign resources to flow-collector

### ISSUE THREAD

**Issue by rmallam** [skupperproject/skupper#1082]
I am trying to spin up skupper with flow collector and the resources params for flow collector with skupper init doesn't seem to work.  The service controller deployment comes up without resources for flow collector container.

  flow-collector-cpu:  
  flow-collector-cpu-limit: 
  flow-collector-memory:
  flow-collector-memory-limit:

**Comment by ajssmith** [comment]
Let me investigate

**Comment by ajssmith** [comment]
Will be fixed in #1076

**Comment by ajssmith** [comment]
merged
