### ISSUE TITLE
Service controller and definition monitor race against modified service

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#1091]
Annotate a deployment (using `skupper.io/proxy`) then wait for skupper to create a service for it.
Next try to update the service, using a basic service yaml (without any skupper label or annotation).

You can see that there Definition Monitor and Service controller are racing to update the service,
which leads to target selectors changing constantly.

**Comment by fgiorgetti** [comment]
Basically if you expose using the CLI, but a service with the same name already exists, this is also happening.

**Comment by grs** [comment]
> Basically if you expose using the CLI, but a service with the same name already exists, this is also happening.

In this case, skupper should 'win', unless you have some gitops reconciliation that is continually trying to correct the service to what it believes it should be.

Ultimately, this is a conflict that isn't solvable. We could simply have the controller avoid updating a service it did not create in the first place (as indicated by label). The annotation on the deployment would then not be realised properly if 'blocked' by the existence of a service.

**Comment by fgiorgetti** [comment]
> In this case, skupper should 'win', unless you have some gitops reconciliation that is continually trying to correct the service to what it believes it should be.

Correct. In this scenario there is no gitops reconciliation in place, it is purely a dispute between the controller
and the definition monitor.

I have a fix ready to be evaluated. It basically changes the way that the original service definitions are
restored, since today, the definition monitor is restoring the original definitions for services that were not
previously annotated themselves. Now the restoration has been delegated to the controller itself.

I will create a PR as soon as test is ready.
