### ISSUE TITLE
Cannot use route as ingress mode for console when main ingress mode is something else.

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#1104]
Options `--ingress=loadbalancer --console-ingress=route --enable-console --enable-flow-collector` do not result in console being exposed via a router as would be expected.

**Comment by kronotheone** [comment]
Hi

I saw the 1.4.0-rc2 release, in which the issue should be solved.
So I've started from a clean setup.
Make sure the skupper operator is uninstalled.
Performed skupper delete. Ensured all Deployments and the ConfigMap are deleted.

Reassured I have the correct binary:

./skupper version                
client version                 1.4.0-rc2

Created a skupper site

./skupper init --console-auth openshift --enable-console --enable-flow-collector --ingress loadbalancer --router-load-balancer-ip 10.xxx.137 --controller-load-balancer-ip 10.xxx.138 --console-ingress route

Result:
All Deployments and the ConfigMap are created
The console is now available

New problem:
The ingress IP is not visible in the token that is needed to connect another skupper site.
Instead, it shows the claims route in the secret:

kind: Secret
metadata:
  annotations:
    skupper.io/generated-by: d0b2ba62-ba83-4536-b883-1e2a0ec761a2
    skupper.io/site-version: 1.4.0-rc2
    skupper.io/url: https://claims-xxxxxxxxxxxx:443/68824438-047f-11ee-8ba3-000c29d008f6
  creationTimestamp: null
  labels:
    skupper.io/type: token-claim
  name: 68824438-047f-11ee-8ba3-000c29d008f6

Is there something wrong with my skupper init command, or something else?

Best regards

**Comment by grs** [comment]
The issue there is that at present the claims handling is considered to be exposed through the console-ingress. I agree this is confusing and have a PR in progress to fix that: https://github.com/skupperproject/skupper/pull/1123

One possible workaround is to use --token-type cert when creating the token. That will result in a full certificate being created and so bypasses the claims step (which retrieves the cert based on a shared secret).

**Comment by kronotheone** [comment]
That workaround works indeed!
