### ISSUE TITLE
Service-controller removed all services in a namespace

### ISSUE THREAD

**Issue by iagodvsantos** [skupperproject/skupper#1115]
We have skupper installations cross-cluster in 6 different namespaces and, yesterday at 6:01 (GMT-03) we noticed that in one of these namespaces, all services created by skupper were removed, and also the `data` configuration on the `skupper-services` configmap.

Trying to dig a bit more to figure out the root cause of the problem we have observed that `skupper-service-controller` removed them (just in one namespace) through K8s audit logs:
```
protoPayload: {
@type: "type.googleapis.com/google.cloud.audit.AuditLog"
authenticationInfo: {
principalEmail: "system:serviceaccount:op:skupper-service-controller"
}
authorizationInfo: [1]
methodName: "io.k8s.core.v1.services.delete"
request: {3}
requestMetadata: {2}
resourceName: "core/v1/namespaces/op/services/network-graphql-digesto-http-cross"
```

At the time I spotted those logs from skupper-router container:
```
"2023/05/18 21:01:09 DELETE io.skupper.router.httpListener network-graphql-digesto-http-cross:3000"
```

And those from the config-sync container:
```
2023/05/18 21:01:08 sync failed: Bridge config is not synchronised yet
2023/05/18 21:01:08 Requeuing op/skupper-internal after error: Bridge config is not synchronised yet
023/05/18 21:01:08 DELETE io.skupper.router.tcpListener network-graphql-digesto-cross:3000
```

However, there were no specific logs from the service-controller itself.

The router is using this version currently: quay.io/skupper/skupper-router:2.1.0

**Comment by iagodvsantos** [comment]
Cool! Thanks, @fgiorgetti.

Does it require the implementation introduced by this [PR](https://github.com/skupperproject/skupper/pull/968) to see the k8s events? 
Because can't we see any events whatsoever from skupper specifically.

**Comment by fgiorgetti** [comment]
Correct. Otherwise you can try running: `skupper debug events`.

**Comment by iagodvsantos** [comment]
Indeed that was problem:
```
1      Service sync aged out service definitions from site                                                         19h59m26s
```

Thanks again @fgiorgetti
