### ISSUE TITLE
[RFE] skupper integration with ServiceMesh

### ISSUE THREAD

**Issue by michaelalang** [skupperproject/skupper#1144]
Trying to get skupper working in an Openshift Cluster with ServiceMesh outbound policy `REGISTRY_ONLY` and mTLS enforced.

The problem with policy restricted and enforced means that no connections are granted without an explicit `ServiceEntry` for it.

Now skupper router tries to establish an AMQP connection to an IP (not sure how the IP is determined) 2 counts less than it's own.
(example: container IP 10.131.0.5 -> AMQP connect to IP 10.131.0.3)
so far so good but unfortunately, ServiceMesh doesn't grant IP addresses and in the particular case, they would be obsolete when the pod reconciles.

The only option I found to get skupper working in a fully restricted and enforced mesh is by excluding the AMQP service Port 55671 globally in the mesh.

It would be nicer if we could set this individually per namespace in the ServiceMesh compared to excluding it generic through a `ServiceEntry` which requires a DNS name to be entered.

I tried checking how skupper could be modified to support such a request and the AMQP service seems to listen on `0.0.0.0` so `localhost` could be an option for that.

**Comment by grs** [comment]
The skupper router will connect to other skupper routers (as defined by links established) and also to any target pods implementing skupper exposed services. The skupper service controller will connect to the router.

The pattern you observe for IPs is just coincidence, based on the order services are created and the way IPs are allocated.

I'm not really sure what you are requesting/suggesting?

**Comment by michaelalang** [comment]
Hi @grs, thanks for the explanation ... what I am observing is the connection to the AMQP `55671` currently is done through an IP address which makes it impossible to be defined as ServiceEntry 

```
# logs from the listener
2023-06-20 15:52:19.526020 +0000 SERVER (notice) Listening on :55671
2023-06-20 15:52:21.387115 +0000 SERVER (info) [C5] Accepted connection to :55671 from 10.129.0.2:53746
```

and the client connecting (10.129.0.2) utilizes the IP and I want to suggest to change that to an FQDN if that is possible.

**Comment by grs** [comment]
The address used will depend on the value of the `ingress` option on the skupper site being linked to and on how the chosen mechanism is configured. E.g. on openshift the default is an openshift route which is always a fqdn. On other cluster types the default is a loadbalancer service, where it could be either a host or an ip, depending on the implementation of loadbalancer on that platform. It can also be configured to use a kubernetes `ingress` or a contour `httpproxy` resource which are also fqdns.

**Comment by michaelalang** [comment]
@grs what I mean is following, 

when starting up the AMQP setup connects to an IP address instead of a Name as seen below 
```$ oc logs -f deploy/skupper-router -c istio-proxy
{"level":"info","time":"2023-06-21T06:47:33.343129Z","scope":"dns","msg":"Starting local udp DNS server on 127.0.0.1:15053"}
{"level":"info","time":"2023-06-21T06:47:33.343390Z","scope":"dns","msg":"Starting local tcp DNS server on 127.0.0.1:15053"}
{"level":"info","time":"2023-06-21T06:47:33.343562Z","scope":"citadelclient","msg":"Citadel client using custom root cert: var/run/secrets/istio/root-cert.pem"}
{"level":"info","time":"2023-06-21T06:47:33.366381Z","scope":"ads","msg":"All caches have been synced up in 132.374198ms, marking server ready"}
{"level":"info","time":"2023-06-21T06:47:33.366968Z","scope":"xdsproxy","msg":"Initializing with upstream address \"istiod-cluster.istio-system.svc:15012\" and cluster \"Kubernetes\""}
{"level":"info","time":"2023-06-21T06:47:33.367050Z","scope":"sds","msg":"Starting SDS grpc server"}
{"level":"info","time":"2023-06-21T06:47:33.450855Z","scope":"xdsproxy","msg":"connected to upstream XDS server: istiod-cluster.istio-system.svc:15012"}
{"level":"info","time":"2023-06-21T06:47:33.469290Z","scope":"cache","msg":"generated new workload certificate","latency":102641966,"ttl":86399530717823}
{"level":"info","time":"2023-06-21T06:47:33.469359Z","scope":"cache","msg":"Root cert has changed, start rotating root cert"}
{"level":"info","time":"2023-06-21T06:47:33.469384Z","scope":"ads","msg":"XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:"}
{"level":"info","time":"2023-06-21T06:47:33.469439Z","scope":"cache","msg":"returned workload trust anchor from cache","ttl":86399530561776}
{"level":"info","time":"2023-06-21T06:47:33.590128Z","scope":"ads","msg":"ADS: new connection for node:skupper-router-c8549f879-jsfmd.mesh24-1"}
{"level":"info","time":"2023-06-21T06:47:33.590259Z","scope":"cache","msg":"returned workload certificate from cache","ttl":86399409746532}
{"level":"info","time":"2023-06-21T06:47:33.590129Z","scope":"ads","msg":"ADS: new connection for node:skupper-router-c8549f879-jsfmd.mesh24-2"}
{"level":"info","time":"2023-06-21T06:47:33.590420Z","scope":"cache","msg":"returned workload trust anchor from cache","ttl":86399409583758}
{"level":"info","time":"2023-06-21T06:47:33.590511Z","scope":"ads","msg":"SDS: PUSH request for node:skupper-router-c8549f879-jsfmd.mesh24 resources:1 size:4.0kB resource:default"}
{"level":"info","time":"2023-06-21T06:47:33.590669Z","scope":"ads","msg":"SDS: PUSH request for node:skupper-router-c8549f879-jsfmd.mesh24 resources:1 size:1.1kB resource:ROOTCA"}
[2023-06-21T06:47:34.140Z] "- - -" 0 UH - - "-" 0 0 7 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:49892 - -
[2023-06-21T06:47:34.141Z] "- - -" 0 UH - - "-" 0 0 7 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:49896 - -
[2023-06-21T06:47:34.149Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:49912 - -
[2023-06-21T06:47:39.155Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:49928 - -
[2023-06-21T06:47:39.156Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:49944 - -
[2023-06-21T06:47:39.159Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:49950 - -
[2023-06-21T06:47:44.169Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:33018 - -
[2023-06-21T06:47:44.171Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:33002 - -
[2023-06-21T06:47:44.193Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:33034 - -
[2023-06-21T06:47:49.185Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:33048 - -
[2023-06-21T06:47:49.203Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:33058 - -
[2023-06-21T06:47:49.207Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.165:55671 10.132.1.190:33072 - -
```

`BlackHoleCluster` means that there's no ServiceEntry in the ServiceMesh for the record which cannot be added as IP address unfortunately ...

and the IP address switches with every restart of the pod accordingly :/ 

```
[2023-06-21T06:50:46.449Z] "- - -" 0 UH - - "-" 0 0 4 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.190:55671 10.132.1.192:43418 - -
[2023-06-21T06:50:46.452Z] "- - -" 0 UH - - "-" 0 0 2 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.190:55671 10.132.1.192:43388 - -
[2023-06-21T06:50:46.454Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.190:55671 10.132.1.192:43402 - -
[2023-06-21T06:50:51.492Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.1.190:55671 10.132.1.192:43422 - -
```

than I have the option to disable the port Meshwide/globally and the connections start working

```
{"level":"info","time":"2023-06-21T06:54:57.552899Z","scope":"ads","msg":"SDS: PUSH request for node:skupper-router-86dc7ffd78-9r428.mesh24 resources:1 size:4.0kB resource:default"}
{"level":"info","time":"2023-06-21T06:54:57.554337Z","scope":"cache","msg":"returned workload trust anchor from cache","ttl":86399445679899}
{"level":"info","time":"2023-06-21T06:54:57.554600Z","scope":"ads","msg":"SDS: PUSH request for node:skupper-router-86dc7ffd78-9r428.mesh24 resources:1 size:1.1kB resource:ROOTCA"}
[2023-06-21T06:55:20.934Z] "- - -" 0 - - - "-" 9396 114192 10281 - "-" "-" "-" "-" "10.132.1.195:5671" inbound|5671|| 127.0.0.6:51217 10.132.1.195:5671 10.132.1.188:34886 - -
[2023-06-21T06:55:24.143Z] "- - -" 0 - - - "-" 9341 114766 10173 - "-" "-" "-" "-" "10.132.1.195:5671" inbound|5671|| 127.0.0.6:45213 10.132.1.195:5671 10.132.1.188:34010 - -
```

unfortunately that also drops the port for the whole cluster and I am looking for an option/feature in skupper to keep the mesh as restrictive as possible ...

**Comment by grs** [comment]
The connection to 55671 is a result of creating a link. The ip or host used comes from the token used in creating that link. That it turn depends on how the site from which the token was obtained was configured. If you use an openshift route for example, then it will be a fully qualified domain name, not an IP address. (How did you link the site responsible for the BlackHoleCluster connection above? If you look at the token used to create the link you will see the url in use)

The connection to 5671 is from the skupper service controller to the skupper router. This uses the skupper-router-local service.

**Comment by grs** [comment]
Can you get the contents of the `skupper-internal` configmap from the namespace where you are seeing the 55671 connections being made from? In that you should see one (or possibly more if there are more links) `connector` element(s). What is the host and port in that?

**Comment by michaelalang** [comment]
sorry for the delay ...busy week I'll try to get you the required information today ...

**Comment by michaelalang** [comment]
@grs  that's an external Cluster connecting through nodePort configuration 

```
        [
            "connector",
            {
                "name": "test",
                "role": "inter-router",
                "host": "cluster2.example.com",
                "port": "32603",
                "cost": 1,
                "sslProfile": "test-profile",
                "maxFrameSize": 16384,
                "maxSessionFrames": 640
            }
        ],
```

if I drop the restrictions from the mesh (but unfortunately that's why I am heading down the rabbit hole) I can see following lines and everything starts working as without a Mesh

```
{"level":"info","time":"2023-06-23T09:17:08.556452Z","scope":"dns","msg":"Starting local udp DNS server on 127.0.0.1:15053"}
{"level":"info","time":"2023-06-23T09:17:08.556586Z","scope":"dns","msg":"Starting local tcp DNS server on 127.0.0.1:15053"}
{"level":"info","time":"2023-06-23T09:17:08.556744Z","scope":"citadelclient","msg":"Citadel client using custom root cert: var/run/secrets/istio/root-cert.pem"}
{"level":"info","time":"2023-06-23T09:17:08.572635Z","scope":"ads","msg":"All caches have been synced up in 126.415621ms, marking server ready"}
{"level":"info","time":"2023-06-23T09:17:08.573091Z","scope":"xdsproxy","msg":"Initializing with upstream address \"istiod-cluster.istio-system.svc:15012\" and cluster \"Kubernetes\""}
{"level":"info","time":"2023-06-23T09:17:08.573188Z","scope":"sds","msg":"Starting SDS grpc server"}
{"level":"info","time":"2023-06-23T09:17:08.645968Z","scope":"xdsproxy","msg":"connected to upstream XDS server: istiod-cluster.istio-system.svc:15012"}
{"level":"info","time":"2023-06-23T09:17:08.714785Z","scope":"cache","msg":"generated new workload certificate","latency":141872585,"ttl":86399285225162}
{"level":"info","time":"2023-06-23T09:17:08.714842Z","scope":"cache","msg":"Root cert has changed, start rotating root cert"}
{"level":"info","time":"2023-06-23T09:17:08.714866Z","scope":"ads","msg":"XDS: Incremental Pushing:0 ConnectedEndpoints:0 Version:"}
{"level":"info","time":"2023-06-23T09:17:08.714940Z","scope":"cache","msg":"returned workload trust anchor from cache","ttl":86399285062958}
{"level":"info","time":"2023-06-23T09:17:08.868689Z","scope":"ads","msg":"ADS: new connection for node:skupper-router-56d7cf47c7-vff4d.test-1"}
{"level":"info","time":"2023-06-23T09:17:08.868766Z","scope":"cache","msg":"returned workload certificate from cache","ttl":86399131238521}
{"level":"info","time":"2023-06-23T09:17:08.868798Z","scope":"ads","msg":"ADS: new connection for node:skupper-router-56d7cf47c7-vff4d.test-2"}
{"level":"info","time":"2023-06-23T09:17:08.868906Z","scope":"cache","msg":"returned workload trust anchor from cache","ttl":86399131098848}
{"level":"info","time":"2023-06-23T09:17:08.869040Z","scope":"ads","msg":"SDS: PUSH request for node:skupper-router-56d7cf47c7-vff4d.test resources:1 size:4.0kB resource:default"}
{"level":"info","time":"2023-06-23T09:17:08.869142Z","scope":"ads","msg":"SDS: PUSH request for node:skupper-router-56d7cf47c7-vff4d.test resources:1 size:1.1kB resource:ROOTCA"}
[2023-06-23T09:17:09.572Z] "- - -" 0 UH - - "-" 0 0 3 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.0.231:55671 10.132.0.232:38584 - -
[2023-06-23T09:17:09.576Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.0.231:55671 10.132.0.232:38586 - -
[2023-06-23T09:17:09.576Z] "- - -" 0 UH - - "-" 0 0 0 - "-" "-" "-" "-" "-" BlackHoleCluster - 10.132.0.231:55671 10.132.0.232:38596 - -
[2023-06-23T09:17:11.432Z] "- - -" 0 - - - "-" 0 0 12 - "-" "-" "-" "-" "10.132.0.232:5671" inbound|5671|| 127.0.0.6:38873 10.132.0.232:5671 10.132.0.233:44922 skupper-router-local.test.svc.cluster.local -
[2023-06-23T09:17:11.432Z] "- - -" 0 - - - "-" 0 0 12 - "-" "-" "-" "-" "10.132.0.232:5671" inbound|5671|| 127.0.0.6:34189 10.132.0.232:5671 10.132.0.233:44920 skupper-router-local.test.svc.cluster.local -
[2023-06-23T09:17:11.440Z] "- - -" 0 - - - "-" 0 0 10 - "-" "-" "-" "-" "10.132.0.232:5671" inbound|5671|| 127.0.0.6:48627 10.132.0.232:5671 10.132.0.233:44928 skupper-router-local.test.svc.cluster.local -
[2023-06-23T09:17:11.440Z] "- - -" 0 - - - "-" 0 0 16 - "-" "-" "-" "-" "10.132.0.232:5671" inbound|5671|| 127.0.0.6:41017 10.132.0.232:5671 10.132.0.233:44930 skupper-router-local.test.svc.cluster.local -
```

**Comment by michaelalang** [comment]
hmm ... well it seem that all communication is working as expected even with those BlackHoleCluster records still showing ... 
is there any documentation on the internal I can read to ensure, this is not causing any problems for production deployments ?

**Comment by grs** [comment]
Ok, so cluster2.example.com will resolve to some ip, but that is the fqdn that you could use to allow outbound connections, right?

There is not really any detailed documentation of internals, but I'm happy to try and explain anything you are concerned about.

**Comment by michaelalang** [comment]
okay, but I have cluster2 defined as service record ... so far the `skupper-router-local.<namespace>.svc.cluster.local` seems to be the crucial item ...
I cannot make any sense of why there's sill some BlackHoleCluster entries eventhough all seems to be working and I added all necessary items (external clusters, ...) 

```
$ skupper -n test status
Skupper is enabled for namespace "test" in interior mode. It is not connected to any other sites. It has 12 exposed services.
$ skupper -n test service status
Services exposed through Skupper:
├─ postgres-cluster2--rw (tcp port 5432)
├─ ds389-ssl (tcp port 636)
├─ mockbin (tcp port 8080)
├─ postgres-cluster2-ro (tcp port 5432)
├─ ds389-004 (tcp port 636)
├─ ds389-plain (tcp port 389)
├─ postgres-cluster2-sso-rw (tcp port 5432)
├─ postgres-cluster2-rw (tcp port 5432)
├─ postgres-sso-rw (tcp port 5432)
├─ ds389-001 (tcp port 636)
├─ ds389-002 (tcp port 636)
╰─ ds389-003 (tcp port 636)
$ skupper -n test link status

Links created from this site:
-------------------------------
Link test is active

Currently active links from other sites:
----------------------------------------
context deadline exceeded
```
since there's no active links I assume, the timeout there isn't nice but not dramatic :D 
I verified that the exposed service are access able through skupper ...

**Comment by grs** [comment]
Can you determine what pod has IP 10.132.0.232 ?

**Comment by michaelalang** [comment]
that should be in the OVN network the router/gateway 
```
$ ovs-appctl ovs/route/lookup 10.132.0.232
src 10.132.0.2
gateway ::
dev ovn-k8s-mp0
```

**Comment by grs** [comment]
Did you link another site to this one?

**Comment by grs** [comment]
So you are linking cluster 1 to cluster 2 *and* cluster 2 to cluster 1? If so, might that second link what is showing up as the blackholecluster, given that it is originating from the router.gateway? That second link is not necessary however, if the first link already links the two sites, which is why everything works.

**Comment by michaelalang** [comment]
No I just created one link from Cluster1 to Cluster 2 (I am aware of the memory leak we have in the RH Operator image of skupper)

**Comment by grs** [comment]
55671 is the inter-router pod. I.e. only another skupper router should be trying to connect on that port (and then only if this site is using a loadbalancer service for skupper-router). The fact that the source seems to be the ovn router/gateway suggests that it is initiated from something outside the cluster.

However, as I understand it, everything is working with your desired configuration?

**Comment by michaelalang** [comment]
It seems to be working ... it could be the istio-proxy which tries to check on the service for health ... well don't bother too much ...

Thanks for your patience and support I think, the RFE isn't necessary at all with the items you provided 
All the best and kind regards
Michi

**Comment by michaelalang** [comment]
thank you for your support I consider the RFE at the moment not necessary.

**Comment by grs** [comment]
thank you for trying it all out and getting it to work!

**Comment by michaelalang** [comment]
found it, it's the `connection` back that creates the blackholecluster logs ... I'll add an PR for a new example accordingly

**Comment by grs** [comment]
what is the connection back?

**Comment by michaelalang** [comment]
right now I end up with following rule set  (<test> test as namespace)

* claims-skupper-<test>.apps.cluster1.example.com  # naming depending on namespace
* claims-<test>.apps.cluster2.example.com  # naming depending on route/ingress 

* skupper-inter-router-<test>.apps.cluster1.example.com
* skupper-inter-router-<test>.apps.cluster2.example.com

* skupper-router-<test>.apps.cluster1.example.com
* skupper-router-<test>.apps.cluster2.example.com

so assuming I check on logs on cluster1, without the cluster2 entries I see the blackholecluster logs which I called `connection back`

**Comment by michaelalang** [comment]
@grs FYI if you are interested, that is how I got it working ... https://github.com/michaelalang/ossm-rhai-kafka-demo

**Comment by grs** [comment]
@michaelalang thank you!
