### ISSUE TITLE
skupper cli is not enforcing --console-auth option

### ISSUE THREAD

**Issue by bryonbaker** [skupperproject/skupper#1149]
The skupper cli documentation states that `--console-auth=internal` is a mandatory switch if you specify either of the other options: `--console-user` or `--console-password`

However, the following command is accepted:
'skupper init --enable-console --enable-flow-collector --console-password password --console-user admin'
(This command is defaulting to _internal_)

The switch existence either needs to be enforced or update the documentation to state that the default is 'internal'.

Skupper version: 1.4.1
OCP version 12.4.5

**Comment by pwright** [comment]
@bryonbaker I'm not seeing where it says `--console-auth=internal` is a mandatory switch if ....


What i do see is ` Valid only when --console-auth=internal` and I think that's the correct phrase, is there somewhere else you saw 'mandatory'? Should we change to ` Valid only when --console-auth=internal (default)` to avoid folks tripping on this?
