### ISSUE TITLE
Tokens created with type cert have a static name

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#1154]
If a token is created using `skupper token create --token-type cert my-token.yaml`,
skupper is setting the `Secret` name to `skupper`. With that if you generate multiple
secrets, for different clusters, and apply them all to a given namespace, only one link
will be defined, as secret `skupper` will be replaced.

It would be good to use a distinct secret name, probably based on the site-id.

**Comment by grs** [comment]
Note that there is a --name option that can be used to override the default. That said I would accept the current choice of default is not necessarily optimal.

**Comment by fgiorgetti** [comment]
Closing as the `--name` flag seems to take care of it.
@DendoD96 please let us know if you have any concern.
