### ISSUE TITLE
Rename existing "integration" tests to system tests?

### ISSUE THREAD

**Issue by nicob87** [skupperproject/skupper#117]
- Currently we have normal GO unit-test as the language normally  supports.
- Then we have a special folder "test" in the project:
```
$ tree test
test
├── cluster
│   ├── cluster_test_runner.go
│   └── cluster_test_runner_test.go
└── integration
    ├── connecting_sites
    │   ├── connecting_sites.go
    │   └── connecting_sites_test.go
    ├── tcp_echo
    │   ├── tcp_echo.go
    │   └── tcp_echo_test.go
    └── van_router_create_test.go
```
"cluster" folder is a library used by the currently existing integration tests.
"integration" contains what we call now "integration tests"

and to run those integration tests we are using a particular built-in golang flag:
```
$ go test -tags=integration -v ./test/integration/...
```
This matches  a header in the *_test.go files:
```
$ head -n 1 test/integration/tcp_echo/tcp_echo_test.go 
// +build integration
```

- Proposal is to rename "integration" to "system", this implies renaming the folder, and also not using the "integration" tag anymore.

- In the future, if we have new real integration tests, we can create the integration tests kind again as a different kind of testing to the "system" tests.

**Comment by grs** [comment]
In what way would 'real' integration tests by different from what we have now? (I'm not sure the distinction is that important. However I'm not opposed to a change if others feel it is needed.)

**Comment by nicob87** [comment]
- The same as @grs  I am not opposed to any change, or no change.
- The exact definition  of what is integration and what is not, some times is not clear, anyway... the overall idea is something like this image: 
Just adding some doc:
https://medium.com/@lawrey/unit-tests-ui-tests-integration-tests-end-to-end-tests-c0d98e0218a6

![image](https://user-images.githubusercontent.com/13121406/88223132-5d620e00-cc3d-11ea-9c7f-8a6dd8f7b0ff.png)

So the classification depends on integration of components being tested, and test speed, and context or product itself.
A unit-test may be a simple test that tests a method in a class, and an integration test may be a test that uses two classes/objects interacting.

- I.e.: the kubernetes project, has integration tests, and e2e tests as different kind of tests.
in what they call integration tests, they do things like creating only a master node, and hitting the master node api.
in what they call e2e they create a full cluster with all the nodes, and use it.

integration:
https://github.com/kubernetes/kubernetes/blob/master/test/integration/
https://github.com/kubernetes/kubernetes/blob/master/test/integration/apimachinery/watch_restart_test.go#L73

e2e:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md
https://github.com/kubernetes/kubernetes/tree/master/test/e2e
 
- anyway I think also there was an idea of calling this "system" test ... 
https://www.guru99.com/system-testing.html
```
What is System Testing?
SYSTEM TESTING is a level of testing that validates the complete and fully integrated software product. The purpose of a system test is to evaluate the end-to-end system specifications. Usually, the software is only one element of a larger computer-based system. Ultimately, the software is interfaced with other software/hardware systems. System Testing is actually a series of different tests whose sole purpose is to exercise the full computer-based system. 
```

It seems theoretically "system testing" is something between integration and e2e ... 
 
- So, it is clear there is not a hard division, IMHO, a real integration test would be something of lower level that the current integration tests, that are more like e2e...

**Comment by fgiorgetti** [comment]
I believe I am on the same page as you guys, neutral to the restructuring.
If we go ahead, what would be the new structure for organizing the different levels of tests?
Would it be like: integration, system and e2e?
Independently of going ahead with restructuring or not, it would also be interesting to document
(README) each directory, explaining the purpose for the tests that each one will be holding.
