### ISSUE TITLE
podman: skupper token create error

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#1179]
$ skupper token create ~/token.yaml 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x141f670]

goroutine 1 [running]:
main.(*SkupperPodmanToken).Create(0xf71780?, 0xc0003c5db0?, {0xc00007e960?, 0x0?, 0x0?})
        /home/circleci/project/cmd/skupper/skupper_podman_token.go:25 +0x50
github.com/spf13/cobra.(*Command).execute(0xc000142dc0, {0xc00007e940, 0x1, 0x1})
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dc580)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x37d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        /home/circleci/project/cmd/skupper/skupper.go:1095 +0x25

**Comment by pwright** [comment]
@fgiorgetti I had already created this issue :wink:

**Comment by fgiorgetti** [comment]
@pwright I believe this PR https://github.com/skupperproject/skupper/pull/1222
should fix this issue.
