### ISSUE TITLE
In version 2.5.0, skupper-router will remove the `_asan` and `_tsan` binaries from the container image

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper#1252]
* https://github.com/skupperproject/skupper-router/issues/1267

This change requires update on the skupper side, regarding

https://github.com/skupperproject/skupper/blob/06f42e106da2a307f4853925030286b432e77edc/cmd/site-controller/README.md?plain=1#L39C1-L41

and

https://github.com/skupperproject/skupper/blob/06f42e106da2a307f4853925030286b432e77edc/cmd/skupper/skupper.go#L430-L434

This change means we are effectively undoing what was done in

* https://github.com/skupperproject/skupper/pull/742

Do we want to reinstate valgrind? (It has only image-size costs, not image build time costs like the sanitizers have. Image build time is the reason why skupper-router wants to drop sanitized binaries.)

**Comment by ganeshmurthy** [comment]
Now that a fix for https://github.com/skupperproject/skupper-router/issues/1267 has been merged, this bit of code can be removed from skupper
