### ISSUE TITLE
Incompatibility of 1.5.0 CLI with previous versions of the skupper operator

### ISSUE THREAD

**Issue by nluaces** [skupperproject/skupper#1281]
After using the skupper operator (1.4.3-rh-6) a user got into the following error running 1.5.0 skupper with `skupper status command`
```
$ skupper status
Error: configmaps "skupper-network-status" not found
```
The problem is that the 1.5.0 relies on the existence the configmap `skupper-network-status`, that is not contemplated in previous versions.

Provide more information about what is happening to the user.

**Comment by waldner** [comment]
If I might add, it also requires glibc versions that make it not suitable to run on (not too) old operating systems.

```
$ ./skupper 
./skupper: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./skupper)
./skupper: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./skupper)
```

This is with Rocky linux 8.9.

**Comment by nmcconom** [comment]
I also had to revert to using version 1.4.x because of the GLIBC requirements on a RH 8.6 machine

**Comment by nluaces** [comment]
Hi @nmcconom and @waldner, thanks for confirming it, the problem that both of you are mentioning is a known issue that we expect to solve in following versions thanks to this PR: https://github.com/skupperproject/skupper/pull/1288

That problem is not related with this issue (#1281), but again, thanks for letting us know.

**Comment by waldner** [comment]
I confirm that the libc version problem is solved. Thanks

**Comment by waldner** [comment]
However, this is still happening, even with 1.5.1:

```
❯ skupper status -n myns
Error: configmaps "skupper-network-status" not found
```
Not sure it's expected.

**Comment by nluaces** [comment]
The fix is not available for 1.5.1, but it is going to be in the next release. Thanks.

**Comment by waldner** [comment]
Will the fix be just a better error message or will it include the ability for 1.5.x to work with lower versions?

**Comment by waldner** [comment]
Also the new error message points to documentation at `https://skupper.io/docs/index.html` but I don't see any upgrade instructions there, unless they are also added with a future PR.
