### ISSUE TITLE
GLIBC error when running skupper install command on cloudshell

### ISSUE THREAD

**Issue by sakmathur** [skupperproject/skupper#1286]
With the new updated skupper version, the install command looks for GLIBC_2.32 and GLIBC_2.34 which isn't on the cloud shell running version GLIBC_2.17. As a result, we can't use cloudshell for skupper installation both in IBM and AWS cloudshell.

curl https://skupper.io/install.sh | sh
ERROR: 
skupper: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by skupper)
skupper: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by skupper)

**Comment by nluaces** [comment]
Hi @sakmathur in which OS are you running Skupper?

**Comment by nluaces** [comment]
Hi @sakmathur, this is happening because 1.5.0 Skupper is built on golang 1.20 [1]. 

For now, the workaround is to use 1.4.4 Skupper version.


[1]https://github.com/golang/go/issues/58550

**Comment by sakmathur** [comment]
I was suspecting the version difference, thanks for confirming. Is there a similar script to install 1.4.4 version, like we use for default install?
curl https://skupper.io/install.sh | sh

**Comment by nluaces** [comment]
@sakmathur unfortunately not for now, you can download the 1.4.4 version here: https://github.com/skupperproject/skupper/releases/tag/1.4.4

**Comment by sakmathur** [comment]
That was quick, thanks @nluaces
