### ISSUE TITLE
Remove deprecated usages of `io/ioutil` package

### ISSUE THREAD

**Issue by c-kruse** [skupperproject/skupper#1300]
We use the deprecated go standard library `io/ioutil` package extensively in the project. I'd suggest we migrate away from this package. Would be a very low effort change to script, a simple find/replace + fixing imports.

Trying to keep the cosmetic suggestions to a minimum, but couldn't help myself on this one. I think we are safe to keep these usages as-is if that's everyone's preference.

**Comment by Akasurde** [comment]
@c-kruse I would like to work on this. Please let me know if it works for you. Thanks.

**Comment by c-kruse** [comment]
@Akasurde  we would appreciate that!

**Comment by Akasurde** [comment]
@c-kruse @fgiorgetti  Thanks
