### ISSUE TITLE
Move functionality of `manifest` command into a `skupper` cli subcommand

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#1303]
The information on the hard-coded and on the computed images  used by the `skupper` cli would be very valuable for testing skupper and also for operational use.

This is a request to move the functionality that today exists in `manifest` into a subcommand of `skupper`, so the ability to generate the images manifest is readily available to anyone using skupper.  An alternative would be to have the functionality as an optional/alternate behaviour for the sub command `version`.

For testing, an example of use would be to validate that the images used after an update are as expected.  For operation, that could be used in 'disconnected' scenarios, for pre-pulling the downloads in an automated way.

Today, we can download the manifests from the release pages, but that is not as straightforward as getting the information straight out of the command that is used for all skupper operation.

**Comment by bryonbaker** [comment]
+1 vote for this issue.

We need a way for people to know what images are required to be pulled into corporate container registries. Here is a good example of the problem. In this scenario skupper has only been used for podman sites.

```
$ skupper --platform kubernetes version
client version                 1.4.4-rh-1
transport version              not-found (no configuration has been provided)
controller version             not-found (no configuration has been provided)
$ skupper --platform podman version
client version                 1.4.4-rh-1
transport version              [registry.redhat.io/service-interconnect/skupper-router-rhel9:2.4.3](http://registry.redhat.io/service-interconnect/skupper-router-rhel9:2.4.3) (sha256:1c69e307c6fa)
```

skupper version is only showing "what has been pulled", not "what is needed to be pulled for the current skupper release" into your internal repo. At the moment you need to read through the operator yaml to work out what the manifest is for Kubernetes, and I have no idea where to kind the podman site config.
