### ISSUE TITLE
skupper init --platform podman is not using podman context

### ISSUE THREAD

**Issue by bryonbaker** [skupperproject/skupper#1312]
When using the same console for configuring a podman site and kubernetes site, the skupper init is not recognising the --platform podman option and instead attempts to init in the kubernetes context.

 

$ skupper switch kubernetes

$ skupper init --platform kubernetes --site-name K8s --enable-console --enable-flow-collector --console-auth=internal --console-user=admin --console-password=password

Skupper is now installed in namespace 'comm'.  Use 'skupper status' to get more information.

$ skupper init --site-name MASTER --platform podman --ingress-host 10.10.10.48

Secret already exists:  skupper-local-server
Secret already exists:  skupper-local-client
Secret already exists:  skupper-service-client
Secret already exists:  skupper-console-users
Secret already exists:  skupper-site-server
Skupper is now installed in namespace 'comm'.  Use 'skupper status' to get more information.

However, this works:

$ skupper delete --platform kubernetes
Skupper is now removed from 'comm'.
$ skupper init --platform kubernetes --site-name K8s --enable-console --enable-flow-collector --console-auth=internal --console-user=admin --console-password=password
Skupper is now installed in namespace 'comm'.  Use 'skupper status' to get more information.

$ skupper switch podman
$ skupper init --site-name MASTER --platform podman --ingress-host 10.10.10.48
It is recommended to enable lingering for bryon, otherwise Skupper may not start on boot.
Skupper is now installed for user 'bryon'.  Use 'skupper status' to get more information.

Version information:
$ skupper version
client version                 1.5.0
transport version              quay.io/skupper/skupper-router:2.5.0 (sha256:55f014d0fcf4)
controller version             quay.io/skupper/service-controller:1.5.0 (sha256:11a88e11ee66)
config-sync version            quay.io/skupper/config-sync:1.5.0 (sha256:6a8f5846a805)
flow-collector version         quay.io/skupper/flow-collector:1.5.0 (sha256:f07ea035141f)

**Comment by gabordozsa** [comment]
This might be closed now as per https://github.com/skupperproject/skupper/pull/1451#issuecomment-2072966500 (cc. @fgiorgetti )
