### ISSUE TITLE
Skupper init not working for regular users

### ISSUE THREAD

**Issue by varodrig** [skupperproject/skupper#1319]
**Describe the bug**
A regular user cannot run skupper init even with admin rights on the namespace.

**How To Reproduce**
1) login in openshift as non cluster admin, but as a user.
2) oc  new-project test 
3) skupper init
will return:
  Error: [roles.rbac.authorization.k8s.io](http://roles.rbac.authorization.k8s.io/) "skupper-service-controller" is forbidden: user "user1" (groups=["system:authenticated:oauth" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
  {APIGroups:["[route.openshift.io](http://route.openshift.io/)"], Resources:["routes/custom-host"], Verbs:["get" "list" "watch"]}
  [5:59](https://redhat-internal.slack.com/archives/D069DAJFVRC/p1702421969709229)
  when login with kubeadmin on the same cluster and same namespace works with no issues.
  [5:59](https://redhat-internal.slack.com/archives/D069DAJFVRC/p1702421984811199)

**Expected behavior**
When loggin as cluster admin the command works fine:
skupper init
Waiting for status...
Skupper is now installed in namespace 'start'.  Use 'skupper status' to get more information.

Review roles. It should work for any user with no more than admin rights for the namespace. Worst case it'll only work if I am the admin of that namespace.

**Environment details**
 - Skupper CLI: 1.51
 - Skupper Operator (if applicable): N/A
 - Platform: Openshift 4.14 (Single Node and OpenShift on AWS)

**Additional context**

**Comment by jiridanek** [comment]
@varodrig Hi, looks like you somehow did not fill in details of your actual issue the issue template ;P ^^^

**Comment by varodrig** [comment]
added the details now. let me know if you have any comments/questions @jiridanek

**Comment by jiridanek** [comment]
Possibly relevant PRs/issues
* https://github.com/skupperproject/skupper-operator/issues/21
* https://github.com/skupperproject/skupper/pull/1265

**Comment by fgiorgetti** [comment]
The account being used to initialize Skupper, does not seem to have permission to manage the respective resource
listed above inside the namespace: `APIGroups:["[route.openshift.io](http://route.openshift.io/)"], Resources:["routes/custom-host"]`.

Try adding a rule for this resource as part of your role and see if it helps.

**Comment by varodrig** [comment]
I cannot change that role, that's the admin role used across openshift platform. This role is the role assigned for the user when the user creates the namespace. @fgiorgetti

**Comment by fgiorgetti** [comment]
@varodrig this is a valid issue. Using the `developer` account is causing the initialization to fail.
We will look into this. Thank you!
