### ISSUE TITLE
Help users determine where to focus effort

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#135]
After creating connection, but not getting data to flow,  I felt that cli wasn't telling me what the issue was.
If you have everything working cli reports that services are exposed, but if you don't have services exposed, the cli is silent...

How about 

```
Skupper is enabled for namespace "project-name" in interior mode. The "east" site is connected to 1 other site and has 0 exposed services.
```

three changes:
- always report connections, even if there are none
- always report exposed services, even if there are none
- report site name if exists

**Comment by grs** [comment]
Which version of the client was this with? I see 'No services are exposed' reported if there are no exposed services using latest client (including release 0.3.0). Likewise if it is not connected to any other sites it states 'It is not connected to any other sites.'

**Comment by pwright** [comment]
You're right, all is good in 0.3 re services/connections, which only leaves site name.
If you 
```skupper init --site-name public1```

how would you retrieve site-name later?

**Comment by grs** [comment]
One option is https://github.com/skupperproject/skupper/pull/151 (mentions site name only if it differs from namespace to avoid unnecessary noise).
