### ISSUE TITLE
Ungraceful failures on console, when prometheus deployment did not come up

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#1374]
**Describe the bug**

If the prometheus pod never started, when clicking on the Services tab in the console will produce a client side error:

```
An error occurred on client side
(intermediate value).data is undefined
fetchTcpActiveFlowsByService@https://10.110.178.49:8010/js/topology-fe825df8794806626c4a.bundle.js:1:4112 
``` 

**How To Reproduce**

Export `PROMETHEUS_SERVER_IMAGE` to something invalid, to make it not come up.

    $ export PROMETHEUS_SERVER_IMAGE="x/y"

Initialize Skupper with Console and Flow Collector enabled

    $ skupper init --enable-console --enable-flow-collector

Open the console, and click on 'Services'

**Expected behavior**

If, instead, the Prometheus deployment was stopped after coming up (`k scale deployment skupper-prometheus --replicas 0`), the console presents a nice 'Network Error' message, with instructions for debugging.  That's the kind of behavior that would be expected.

This is a convoluted way of forcing this issue.  However, there were some other situations where the Prometheus deployment did not start, so it would be useful to guard for that situation.

**Environment details**
 - Skupper CLI: 1.5.3
 - Skupper Operator (if applicable): N/A
 - Platform: Minikube

**Additional context**

N/A

**Comment by hash-d** [comment]
@bartoval FYI

**Comment by bartoval** [comment]
https://github.com/skupperproject/skupper/pull/1375
