### ISSUE TITLE
skupper upgrade failing from 1.2.8 to 1.5.3

### ISSUE THREAD

**Issue by ukumar009** [skupperproject/skupper#1376]
**Describe the bug**
I am working on updating skupper version from 1.2.8 to 1.5.3. I am seeing an error and skupper won't upgrade.

**How To Reproduce**
1. Install skupper `1.2.8` version with the following site-config map:
```
  console: "false"
  ingress: none
  name: skupper-site-name
  router-console: "false"
  router-debug-mode: "false"
  router-logging: info
  router-mode: edge
  service-controller: "true"
  service-sync: "true"
```
2. Upgrade skupper to `1.5.3` version with the same site-config map. 

3. seeing the following error in site-controller logs:
```
 Version update check failed for namespace "ns-abc": services "skupper-router" not found
```

**Expected behavior**
site-controller should update all components from 1.2.8 to 1.5.3 version.

**Environment details**
 - Skupper CLI: 1.5.3
 - Skupper Operator (if applicable): 1.5.3
 - Platform: kubernetes

**Additional context**

**Comment by grs** [comment]
Fixed in #1378
