### ISSUE TITLE
Unexposed service does not get removed from bridge server (e.g. persists in console)

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper#141]
1. Step to deploy simple http backend:

kubectl create deployment hello-world-backend --image quay.io/skupper/hello-world-backend
skupper expose deployment hello-world-backend --port 8080 --protocol http

2. Query to https://skupper-controller-skupper.127.0.0.1.nip.io/DATA returns

{
    "sites": [
        {
            "site_name": "skupper",
            "site_id": "a53dd1df-d023-11ea-9180-8c1645a1bc1c",
            "connected": [],
            "namespace": "skupper",
            "url": "skupper-inter-router-skupper.127.0.0.1.nip.io",
            "edge": false
        }
    ],
    "services": [
        {
            "address": "hello-world-backend",
            "protocol": "http",
            "targets": [
                {
                    "name": "hello-world-backend-b856f74fb-fs6q5",
                    "target": "hello-world-backend",
                    "site_id": "a53dd1df-d023-11ea-9180-8c1645a1bc1c"
                }
            ],
            "requests_received": [],
            "requests_handled": []
        }
    ]
}

3. Unexpose the service

skupper unexpose deployment hello-world-backend

4. Verified removal from skupper-internal config map

data:
  bridges.json: '[]'

5. Query to https://skupper-controller-skupper.127.0.0.1.nip.io/DATA continues to return

{
    "sites": [
        {
            "site_name": "skupper",
            "site_id": "a53dd1df-d023-11ea-9180-8c1645a1bc1c",
            "connected": [],
            "namespace": "skupper",
            "url": "skupper-inter-router-skupper.127.0.0.1.nip.io",
            "edge": false
        }
    ],
    "services": [
        {
            "address": "hello-world-backend",
            "protocol": "http",
            "targets": [
                {
                    "name": "hello-world-backend-b856f74fb-fs6q5",
                    "target": "hello-world-backend",
                    "site_id": "a53dd1df-d023-11ea-9180-8c1645a1bc1c"
                }
            ],
            "requests_received": [],
            "requests_handled": []
        }
    ]
}

6.  Inspection of service-controller logs shows bridge data qdr.record still contain service record

SiteQuery([a53dd1df-d023-11ea-9180-8c1645a1bc1c/skupper-site-query])
2020/07/27 16:23:04 Bridge data: []qdr.Record{qdr.Record{"address":"hello-world-backend", "host":"172.17.0.11", "hostOverride":interface {}(nil), "identity":"hello-world-backend@172.17.0.11", "metrics":map[string]interface {}{"address":"hello-world-backend", "egress":map[string]interface {}{"by_originating_site":map[string]interface {}{}, "by_server":map[string]interface {}{}, "bytes_in":0, "bytes_out":0, "details":map[string]interface {}{}, "latency_max":0, "requests":0}, "ingress":map[string]interface {}{"by_client":map[string]interface {}{}, "bytes_in":0, "bytes_out":0, "details":map[string]interface {}{}, "latency_max":0, "requests":0}, "protocol":"http"}, "name":"hello-world-backend@172.17.0.11", "port":0x1f90, "siteId":"a53dd1df-d023-11ea-9180-8c1645a1bc1c", "type":"org.apache.qpid.dispatch.router.httpConnector"}, qdr.Record{"address":"hello-world-backend", "identity":"hello-world-backend", "metrics":map[string]interface {}{"address":"hello-world-backend", "egress":map[string]interface {}{"by_originating_site":map[string]interface {}{}, "by_server":map[string]interface {}{}, "bytes_in":0, "bytes_out":0, "details":map[string]interface {}{}, "latency_max":0, "requests":0}, "ingress":map[string]interface {}{"by_client":map[string]interface {}{}, "bytes_in":0, "bytes_out":0, "details":map[string]interface {}{}, "latency_max":0, "requests":0}, "protocol":"http"}, "name":"hello-world-backend", "port":0x400, "siteId":"a53dd1df-d023-11ea-9180-8c1645a1bc1c", "type":"org.apache.qpid.dispatch.router.httpListener"}}

**Comment by grs** [comment]
I *think* it does get removed, but it takes a while for it to happen. The configmap is not immediately exported to all the pods that mount it, that happens only periodically. Once it does get updated within the pod, it looks to me like it is correctly removed from the exposed data.

**Comment by grs** [comment]
Actually, I take that back there is something odd going on...

**Comment by fgiorgetti** [comment]
I believe I can start working on task #130, which is supposed to address this exact issue.

**Comment by grs** [comment]
This is a bug in the bridge-server whereby if the config file changes to have no elements of a given type, the previously configured entities are not deleted. I.e. it only affects the case where the last service is unexposed (and no others are exposed).

I have pushed a fix for quay.io/skupper/bridge-server:latest
