### ISSUE TITLE
Add expiry date time to token yaml

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#1415]
**Is your feature request related to a problem? Please describe.**
I sometimes create default tokens and then get distracted before using them.
When I do use them, they are invalid

**Describe the solution you'd like**
If the token yaml had more information, eg time created and token duration that would help me avoid wasting time 
think about:

- did the link fail because I've run out of time or because it was already used?
- is connectivity possible between these two sites

**Describe alternatives you've considered**
An expiry date time
No of uses 

**Additional context**
While this doesn't solve the problem of creating a link to the wrong site, because you've mixed up tokens it might be a help when the urls are long and all look the same at a glance.

**Comment by lynnemorrison** [comment]
I'm new to skupper and was looking at issues with the label "good first issue" to start working on skupper. 

I created a token that can be used 4 times:
`skupper token create --name test3 -p test_pass --expiry 10m0s ~/test3.token --uses 4`

I created three links, you can see there were 3 claims made and one still remaining, there is a claim expiration and time created.
```
kubectl get secret -o yaml test3
apiVersion: v1
data:
  password: dGVzdF9wYXNz
kind: Secret
metadata:
  annotations:
    skupper.io/claim-expiration: "2024-04-19T15:02:01-04:00"
    skupper.io/claims-made: "3"
    skupper.io/claims-remaining: "1"
    skupper.io/site-version: 1.6.0
  creationTimestamp: "2024-04-19T18:52:01Z"
  labels:
    skupper.io/type: token-claim-record
  name: test3
  namespace: west
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: skupper-site
    uid: 940a3811-aa89-4d25-b6dd-da6315951108
  resourceVersion: "86378"
  uid: 9422fa7d-2e2f-4c35-ac96-2325f7190d73
type: Opaque

```

Can you please further explain what you are looking for.   Are you looking for a skupper command vs a kubectl command to show this information?

**Comment by pwright** [comment]
@lynnemorrison  thanks for looking at this issue, how about a field labelled 'original_use_count`? ie communicate the original number, even tho we don't know the current value?

**Comment by grs** [comment]
> how about a field labelled `original_use_count`? ie communicate the original number, even tho we don't know the current value?

What would be the value of that? If it says 1 for example, how does that help? It doesn't tell you if it has been used before or not.

**Comment by pwright** [comment]
I've just received a token from my buddy over in West, previously he gave me tokens with 5 uses as we were experimenting with dev systems. This time we're working on prod systems, I wonder how many uses this token starts with?
OTOH, if this adds any extra work over just adding expiry date, I'd say drop it,.

**Comment by lynnemorrison** [comment]
Original "uses" can be added but I'm not sure if it would be helpful or more confusing.   I think it might be better in the documentation to specify to use the kubernets command to look at the secret.     Or should we add a "skupper token status" command?

Is there any procedure/guidelines/approval that I need to follow when making a CLI output change?  Meaning adding the  Expiration field to the "show link status <name> -v"   command has to be ok'd by someone?

**Comment by grs** [comment]
Perhaps the cli could add an annotation to the token in the file when applying it to indicate that fact? When applying a token that has already been marked as having been applied once, a warning could be printed stating this fact for example.

**Comment by lynnemorrison** [comment]
There is a couple of ways I was thinking to indicate the token has expired:

would it be better to add to the link.Description or add another field to the types.LinkStatus structure or just add "token expired" to the Created field?

description field:
`Status:	Not connected (Failed to redeem claim: No such claim, token has expired)`

user issues "skupper link status -v link"

```
skupper link status link1 -v
 Cost:		0						
 Created:	token expired    						
 Name:		link1						
 Namespace:	east						
 Site:		east-6756d26c-f099-48be-94c8-3a54fddccd25	
 Status:	Not connected (Failed to redeem claim: No such claim)

```
or new field:
```
skupper link status link1 -v
 Cost:			0						
 Created:	
 Token Expiration:	2024-04-24T16:03:25-04:00     						
 Name:			link1						
 Namespace:		east						
 Site:			east-6756d26c-f099-48be-94c8-3a54fddccd25	
 Status:		Not connected (Failed to redeem claim: No such claim)
```
Please let me know which option is preferred, or another option and I'll complete fix.

**Comment by pwright** [comment]
for me, I'd prefer if the token is rejected silently (to prevent any future possible info leakage), and just add expiry time to token when issued.

**Comment by grs** [comment]
I think the link status is the wrong place to include this information. Based on the original problem statement, it should be at the point the token is applied, i.e. on `skupper link create` that any checks and/or warnings/errors occur.

**Comment by Karen-Schoener** [comment]
Out of curiosity, when 2 sites are linked, is it a given that time is set correctly on both sites?

I am wondering: if time is incorrect on the initiating side, then I think the initiating side might (incorrectly) report an expired token.

Just wanted to check my understanding...

**Comment by lynnemorrison** [comment]
I added the expiry time to the error output to make it easier for user to see when the token expired.   The user could also use this time to verify against their local time.

**Comment by Karen-Schoener** [comment]
Would it make sense to add a (optional) check-token-expiry flag to the `link create` command?

That way, if the CLI `link create` is run on site east, then the user on site east has the option to skip this 'token expiry' check.  

I believe that this would eliminate the requirement that time must be synced, say, between the east and west sites.

My concern is the use case: when a piece of software/controller programmatically configures skupper sites and initiates link create requests.

**Comment by lynnemorrison** [comment]
I can see Karen's concern that potentially if the timers are off on the routers that the west router created a token, and then the east router, whose time is off from the west router, checks the token and determines it has expired and issue the new error and doesn't attempt to create the link. 

Should this PR be changes to make the error a warning and just continue trying to create the link.   The west router will fail the link connection if it determines the token has expired.

  
```
skupper link crate ~/token.txt
Warning: Token may have expired 2024-05-06 08:48:23 -0400 EDT
```

**Comment by lynnemorrison** [comment]
@grs @pwright any feedback on changing this from a failure when the router is trying to use a token and believes it has expired to change this to a warning instead of failing the link outright?

**Comment by pwright** [comment]
I like the idea of adding information to the token yaml (passive change) and am concerned about changing the failure logic (active change), because the passive change cannot have unforeseen consequences (other than in user's head)

**Comment by lynnemorrison** [comment]
The code had been changed to add a warning that the token may have expired but the link creation continues.

```
skupper link create ~/token2.txt
Warning: token may have expired, expiration time: 2024-05-07 16:28:44 -0400 EDT
Site configured to link to https://10.97.143.195:8081/42f0aae6-0cb0-11ef-843d-0800275c9d9f (name=link1)
Check the status of the link using 'skupper link status'.

```
the link status command has not been changed.   Would it be beneficial to add a warning her also
or just leave as is?
```
skupper link status

Links created from this site:

	 Link link1 not connected (Failed to redeem claim: No such claim)

Current links from other sites that are connected:

	 There are no connected links

```
