### ISSUE TITLE
Edge sites show as indirect connections even when linked directly on `skupper status -v` output

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#1421]
**Describe the bug**

On a topology with an edge site connected to an interior one, when `skupper status -v` is run from the interior site, the connection is reported as indirect.

**How To Reproduce**

- Create an interior site
- Create an edge site
- Connect edge to interior
- Run `skupper status -v` from the interior site

```
$ skupper status
Skupper is enabled for namespace "dh-pub". It is connected to 1 other site. It has 2 exposed services.

$ skupper status -v
kubernetes:            dh-pub 
mode:                  interior 
site name:             dh-pub 
policies:              disabled 
total connections:     1 
direct connections:    0 
indirect connections:  1 
exposed services:      2 

$ skupper network status
Sites:
├─ [local] 0ed3b1f9-b61d-4445-bcf6-d6d623a7cafd(dh-pub) 
│  namespace: dh-pub
│  site name: dh-pub
│  version: 1.5.3-rh-1
╰─ [remote] d606de9d-cc84-4b52-99bc-68dc2f7b2ea8(dh-prv) 
   │ namespace: dh-prv
   │ site name: dh-prv
   │ version: 1.5.3-rh-1
   ╰─ Linked sites:
      ╰─ 0ed3b1f9-b61d-4445-bcf6-d6d623a7cafd(dh-pub)
         direction: outgoing
$ 
```

**Expected behavior**

The connection is direct, so it should be counted as such?

**Environment details**

 - Skupper CLI: 1.5.3
 - Skupper Operator (if applicable): n/a
 - Platform: openshift 4.13

**Additional context**

n/a

**Comment by hash-d** [comment]
@nluaces FYI

**Comment by nluaces** [comment]
@hash-d , I couldn't reproduce the issue following the steps that you are suggesting:
```
~ » skupper status -v                                                                                 
kubernetes:            private1 
mode:                  interior 
site name:             private1 
policies:              disabled 
total connections:     1 
direct connections:    1 
indirect connections:  0 
exposed services:      0 
```

```
skupper link status                                                                               
Links created from this site:

	 Link link1 is connected

Current links from other sites that are connected:

	 There are no connected links
```

```
~ » kubectl describe configmap skupper-internal                                                       
Name:         skupper-internal
Namespace:    private1
Labels:       <none>
Annotations:  <none>

Data
====
skrouterd.json:
----
[
    [
        "router",
        {
            "id": "private1-${HOSTNAME}",
            "mode": "edge",
            "helloMaxAgeSeconds": "3",
            "metadata": "{\"id\":\"68ab9005-39ed-4aed-8945-320c8c00d1c8\",\"version\":\"main-release-61-gd6f8e80-modified\",\"platform\":\"kubernetes\"}"
        }
    ],
```

Nevertheless, I have noticed in my test and in the output that you have pasted in this issue, that the **router mode is not correct** in the verbose skupper status command option, because it should be `edge` (like the skupper-internal configmap shows) and not `interior`. I am currently investigating that.

Going back to the initial issue, if you are able to reproduce it again, could you check if the link is in status `connected`? the indirect connections also happen when links are created but not connected. Thanks!

**Comment by nluaces** [comment]
@hash-d Oh, you are right, I can see it now. Thanks!

**Comment by nluaces** [comment]
Update:

> I have noticed in my test and in the output that you have pasted in this issue, that the router mode is not correct in the verbose skupper status command option

This was solved in https://github.com/skupperproject/skupper-router/pull/1461

Regarding the issue with direct/indirect connections, the router does not include Link records for edge router connections on the listener side, and the status command is at present relying on that to know how many sites are directly connected with.
