### ISSUE TITLE
skupper init with ingress set to empty string makes LoadBalancer as the default on Openshift

### ISSUE THREAD

**Issue by granzoto** [skupperproject/skupper#1424]
**Describe the bug**
skupper init --ingress '' on Openshift, assumes that LoadBalancer should be used as the default ingress
An empty value should also make skupper pick the default for the proper k8s flavor, in this case, route for OCP.

**How To Reproduce**
On a OCP cluster : 
skupper init --ingress ''

**Expected behavior**
Expect route to be used as the ingress.

**Environment details**
 - Skupper CLI: 1.5.3
 - Skupper Operator : NA
 - Platform: openshift

**Comment by Karen-Schoener** [comment]
Just fyi, I am starting to investigate this ticket.  Thanks, Karen
