### ISSUE TITLE
skupper-service-controller pods crashing when the flow-controller is enabled

### ISSUE THREAD

**Issue by shgovind-rh** [skupperproject/skupper#1443]
**Describe the bug**
Configured the site with a custom CA per instructions [here](https://github.com/skupperproject/skupper-docs/blob/main/kubernetes/index.adoc), however when I issue the command - `skupper init  --enable-console --enable-flow-collector`, the skupper-service-controller pods starts crashing. On inspecting, the logs from `flow-controller` containers show the following

```
2024/04/17 11:06:52 COLLECTOR: Starting Skupper Flow collector controller version 1.6.0
2024/04/17 11:06:52 COLLECTOR: Waiting for Skupper router component to start
2024/04/17 11:06:57 Error getting connect.jsonopen /etc/messaging/connect.json: no such file or directory
```

- Below is the output of the skupper init command
```
$ skupper init  --enable-console --enable-flow-collector
Secret already exists:  skupper-local-server
Secret already exists:  skupper-local-client
Secret already exists:  skupper-service-client
Secret already exists:  skupper-site-server
Waiting for status...
Skupper is now installed in namespace 'products'.  Use 'skupper status' to get more information.
```

- Below is the output of the skupper status command

```
$ skupper status
Skupper is enabled for namespace "products". It is not connected to any other sites. It has no exposed services.
The site console url is:  https://skupper-products.apps.cluster-gnslt....
The credentials for internal console-auth mode are held in secret: 'skupper-console-users'

```

**How To Reproduce**

1.  Configured the site with a custom CA per instructions [here](https://github.com/skupperproject/skupper-docs/blob/main/kubernetes/index.adoc)
2. Create the site with flow-controller enabled by issuing the command - `skupper init  --enable-console --enable-flow-collector`
3. Observe the pods

**Expected behavior**
Skupper site configured correctly with console enables

**Environment details**

- Skupper CLI: 1.6.0
- Skupper Operator (if applicable): 1.4.4-rh-1
- Platform: Openshift

**Comment by nluaces** [comment]
Hi @shgovind-rh, that error happens because something is missing in the data of the secret `skupper-local-client` with the key `connect.json` (which we need to add to our docs, thank you for reporting this!):

```
{
    "scheme": "amqps",
    "host": "skupper-router-local.YOUR_NAMESPACE.svc.cluster.local",
    "port": "5671",
    "tls": {
        "ca": "/etc/messaging/ca.crt",
        "cert": "/etc/messaging/tls.crt",
        "key": "/etc/messaging/tls.key",
        "verify": true
    }
}
```
You need to patch your secret with that information before creating a site with skupper. This is an example:
```
kubectl patch secret skupper-local-client  -p="{\"data\":{\"connect.json\":\"$(echo '{
    "scheme": "amqps",
    "host": "skupper-router-local.YOUR_NAMESPACE.svc.cluster.local",
    "port": "5671",
    "tls": {
        "ca": "/etc/messaging/ca.crt",
        "cert": "/etc/messaging/tls.crt",
        "key": "/etc/messaging/tls.key",
        "verify": true
    }
}'  | base64 | tr -d '\n')\"}}"
```
Let me know if that works for you.

**Comment by shgovind-rh** [comment]
@nluaces Glad to help get the docs better and Thanks for looking into this and providing a solution
