### ISSUE TITLE
service not reported until after sites are linked

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#1444]
**Describe the bug**

I exposed a service after creating a site, and `skupper service status` reported no services 

**How To Reproduce**

1. Create a k8s site
2. expose a service
`skupper expose statefulset nginx-statefulset --headless`
`statefulset nginx-statefulset exposed as nginx-service`

3. check services
```
skupper service status
No services defined
```
4. Create a podman site and linked to k8s site

5. check services

```
skupper service status
Services exposed through Skupper:
├─ nginx-service-0:80 (tcp)
├─ nginx-service-1:80 (tcp)
╰─ nginx-service-2:80 (tcp)
```

**Expected behavior**
Service report should show services even when there's one site

**Environment details**
 - Skupper CLI: 1.6
 - Skupper Operator (if applicable):na
 - 
**Additional context**

**Comment by nluaces** [comment]
Hi @pwright, could you check without any site linking, the local services appear eventually in the output of skupper service status?

**Comment by pwright** [comment]
@nluaces I have tried in a few environments and unable to reproduce. 
In the original environment where I encountered the issue, I waited 20 mins, so I don't believe it was impatience, but it was a one-off.
