### ISSUE TITLE
Disabling service-sync doesn't work as expected

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#1466]
**Describe the bug**

When users `skupper init --enable-service-sync=false` and perform hello-world, the `backend` service is reported on west, without user `skupper service create backend`.

east: `skupper expose deployment/backend --port 8080`  
west:  
```
$ skupper service status
Services exposed through Skupper:
╰─ backend:8080 (tcp)
```

**How To Reproduce**

1. Perform https://github.com/skupperproject/skupper-example-hello-world
but with  `skupper init --enable-service-sync=false`  

2. Check service status on west

**Expected behavior**
No service should be available

but
west:  
```
$ skupper service status
Services exposed through Skupper:
╰─ backend:8080 (tcp)
```

**Environment details**
 - Skupper CLI: 1.5, 1.6, 1.7 
 - Skupper Operator (if applicable): [e.g. 1.5.0, 1.4.3]
 - Platform: minikube

**Additional context**
While the `backend` service is reported, the frontend cannot call the backend

**Comment by nluaces** [comment]
Hi @pwright, I have reproduced what you have seen:

```
~ » skupper service status                                                                            
Services exposed through Skupper:
╰─ backend:8080 (tcp)
```

If you check the verbose mode, you can see that the service is only exposed in one of the sites, the one that has the target.

```
~ » skupper service status -v                                                                         
Services exposed through Skupper:
╰─ backend:8080 (tcp)
   ╰─ Sites:
      ╰─ 552df183-39a6-4e1d-9a7d-e493f8946c86(east)
         │ policy: disabled
         ╰─ Targets:
            ├─ backend:8080 name=backend-778cb759c9-c26hs
            ├─ backend:8080 name=backend-778cb759c9-ktdsh
            ╰─ backend:8080 name=backend-778cb759c9-pt6rs
```
It appears because the service is exposed in some site that belongs to the network. But this could be misleading if the user does not specify the verbose mode. The status command should filter services not exposed in the site by default. 

Thanks for reporting.

**Comment by pwright** [comment]
just to complete the picture, if you later create the service, the verbose status reports:

```
skupper service status -v
Services exposed through Skupper:
╰─ backend:8080 (tcp)
   ╰─ Sites:
      ├─ 4d80f485-52fb-4d84-b10b-326b96e723b2(west)
      │  policy: disabled
      ╰─ 316fbe31-299b-490b-9391-7b46507d76f1(east)
         │ policy: disabled
         ╰─ Targets:
            ╰─ backend:8080 name=backend-9d84544df-rbzjx


```
