### ISSUE TITLE
Allow specifying an existing CA when deploying the site-controller from yamls

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#154]
By doing that, it would enable users to define connection tokens in a git repository in advance, for the edge sites.
This is helpful for people using GitOps operators to maintain their skupper network.

**Comment by grs** [comment]
You would need to know the url through which the site the edges would connect to would expose. With openshift routes that can be predetermined if you know the cluster name and namespace to be used. For other clusters it is not always possible to know in advance.

And once you have the central site, creating a token for an edge is simple and the result can be stored in the git repo for the edge if desired (though I wonder if that would actually be desired?).

**Comment by fgiorgetti** [comment]
That is true. I also believe that storing  the token in a git repo, might not be a good idea,
but the motivation was simply to enable deploying the whole network at once. Maybe we
have to figure out how easy it is to determine the host in advance, using other clusters than
openshift, to understand if it is worth implementing this feature.
