### ISSUE TITLE
Create a new quay organization for the container images used by the e2e tests

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#155]
The e2e tests are going to use images to run protocol tests inside the clusters and for doing so,
it might be useful if we have an organization in quay to store all those images.

**Comment by nicob87** [comment]
This is also related to the release process, when we want to release, we need to "docker login" with authorization to push to quay.io/skupper.

**Comment by hash-d** [comment]
@fgiorgetti, based on the discussion we had earlier today with the team, do you think we can close this issue?  It would be one less on the list, and there is no further action on this, as we'll keep using the main skupper org on Quay.
