### ISSUE TITLE
update listener and connector commands to new status subresources

### ISSUE THREAD

**Issue by nluaces** [skupperproject/skupper#1561]
More information about the new values for the status here: https://github.com/skupperproject/skupper/pull/1539

**Comment by lynnemorrison** [comment]
@grs a couple of questions on status for connectors and listeners.

Once I create a listener, I do see a condition configured.   But no other condition 
```
lynne@lynne-VirtualBox:~/v2_status$ kubectl get listener -n west -o yaml
apiVersion: v1
items:
- apiVersion: skupper.io/v1alpha1
  kind: Listener
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"skupper.io/v1alpha1","kind":"Listener","metadata":{"annotations":{},"name":"backend","namespace":"west"},"spec":{"host":"backend","port":8080,"routingKey":"backend"}}
    creationTimestamp: "2024-08-05T12:35:21Z"
    generation: 1
    name: backend
    namespace: west
    resourceVersion: "46325"
    uid: f4468c7d-6038-461f-bf3a-f9beaef1e33a
  spec:
    host: backend
    port: 8080
    routingKey: backend
  status:
    conditions:
    - lastTransitionTime: "2024-08-05T12:35:28Z"
      message: OK
      observedGeneration: 1
      reason: OK
      status: "True"
      type: Configured
kind: List
metadata:
  resourceVersion: ""

```
For a connector I do not see any condition status, should there be:

```
Lynne@lynne-VirtualBox:~/v2_status$ kubectl get connector -n east -o yaml
apiVersion: v1
items:
- apiVersion: skupper.io/v1alpha1
  kind: Connector
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"skupper.io/v1alpha1","kind":"Connector","metadata":{"annotations":{},"name":"backend","namespace":"east"},"spec":{"port":8080,"routingKey":"backend","selector":"app=backend"}}
    creationTimestamp: "2024-08-05T12:35:43Z"
    generation: 1
    name: backend
    namespace: east
    resourceVersion: "46353"
    uid: 198eee31-08e6-4d56-a56b-822de3b8eb9b
  spec:
    port: 8080
    routingKey: backend
    selector: app=backend
kind: List
metadata:
  resourceVersion: ""

```
But after I've issued and redeemed a token I do see status for the connector, indicating there is one listener with same routing-key.

```
lynne@lynne-VirtualBox:~/v2_status$ kubectl get connector -n east -o yaml
apiVersion: v1
items:
- apiVersion: skupper.io/v1alpha1
  kind: Connector
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"skupper.io/v1alpha1","kind":"Connector","metadata":{"annotations":{},"name":"backend","namespace":"east"},"spec":{"port":8080,"routingKey":"backend","selector":"app=backend"}}
    creationTimestamp: "2024-08-05T12:35:43Z"
    generation: 1
    name: backend
    namespace: east
    resourceVersion: "47312"
    uid: 198eee31-08e6-4d56-a56b-822de3b8eb9b
  spec:
    port: 8080
    routingKey: backend
    selector: app=backend
  status:
    conditions:
    - lastTransitionTime: "2024-08-05T12:44:28Z"
      message: OK
      observedGeneration: 1
      reason: OK
      status: "True"
      type: Matched
    matchingListenerCount: 1
kind: List
metadata:
  resourceVersion: ""
```

So my questions:

1. when in CLI creating a listener I'm just going to look at a condition configured and return success
2. what should I look at for connector?    Just that it exists?
3. When doing an update to a listener/connector if the config change is successful should I expect any change in the conditions?    But if it was not successful, will I see any change in the conditions?  

I was going to add an IsActive routine in pkg/apis/skupper/v1alpha1/types.go for listener to check conditions, like what is done for site commands.
```
func (s *Listener) IsActive() bool {
	return meta.IsStatusConditionTrue(s.Status.Conditions, CONDITION_TYPE_CONFIGURED)
}

```

**Comment by grs** [comment]
@lynnemorrison The connector should reach a configured condition as well. If a selector is used that will be once it has resolved some active pods. Both listener and connector also have a 'matched' condition defined, which is true when there is at least one corresponding binding (i.e. a listener for a connector, a connector for a listener). They are considered 'ready' when they are both configured and matched. The reason for that is that until both these conditions are reached the connector or listener may not actually be usable.

What the appropriate test is from the CLI by default I am not sure. While 'ready' seems to me what users would want, it may take some time to reach that state. For a connector with a selector that matches no pods, or where a connector/listener is not matched, it may not ever reach that state. So it *may* be that simply waiting for the created connector/listener to be configured is what we want the CLI to do by default.

If that is the path we choose, I would prefer to call the method IsConfigured() rather than IsActive() (which is a badly named method left in there by me!).

@nluaces @ssorj thoughts?

**Comment by nluaces** [comment]
>While 'ready' seems to me what users would want, it may take some time to reach that state. For a connector with a selector that matches no pods, or where a connector/listener is not matched, it may not ever reach that state.

@grs I agree on making wait the user just for the configuration of listeners/connectors and suggest to check the status of the resource.

Another question for @grs: if we update a custom resource, is that update being reflected somewhere? is the controller re-configuring the resource again and transitioning its status like when we create a new custom resource?

**Comment by grs** [comment]
> if we update a custom resource, is that update being reflected somewhere? is the controller re-configuring the resource again and transitioning its status like when we create a new custom resource?

If the resource is changed then any necessary reconfiguration will be done and the observedGeneration in the condition should be updated.
