### ISSUE TITLE
Spinner breaks my shell cursor.

### ISSUE THREAD

**Issue by c-kruse** [skupperproject/skupper#1585]
**Describe the bug**
When a skupper command with a spinner doesn't complete successfully (usually I get impatient and ^C it) the cursor in my shell disappears and I have to run `reset` to get it back (though I'm sure there's probably a more clever way to go about it.)

I suspect that it is our usage of the spinner library sending control codes but not cleaning up after ourselves.

**How To Reproduce**
Steps to reproduce the behavior: Run a long skupper command with a spinner like `skupper init` and kill the process.

otherwise run this little gizmo.
```
package main
import (
        "context"
        "fmt"
        "os"
        "os/signal"
        "github.com/skupperproject/skupper/pkg/utils"
)
func main() {
        ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
        defer cancel()
        err := fmt.Errorf("nope")
        go func() {
                if err := utils.NewSpinner("kill this process and notice your bash cursor being missing", 20, func() error { return err }); err != nil {
                        fmt.Printf("spinner finished with error: %s\n", err)
                }
        }()
        <-ctx.Done()
        fmt.Println("exiting")
}
```

**Expected behavior**
I'd love for it to clean up after itself consistently.

**Environment details**
 - Skupper CLI: 1.7.3

**Additional context**

**Comment by c-kruse** [comment]
@nluaces you ever notice this?
[Screencast from 2024-08-12 10-07-29.webm](https://github.com/user-attachments/assets/f7ecd301-b0fd-4563-87cc-4ee4c943afe3)

**Comment by nluaces** [comment]
@c-kruse I have not! but thank you for reporting this issue, as it has to be fixed as well for V2

**Comment by c-kruse** [comment]
Though this bug is very minor, I think the real root of the issue is probably part of something we should look at more closely for v2: gracefully handling signals.

Aside from leaving shells in inconvenient states, we are probably liable to be leaving whatever transactions we're performing in limbo in some places: even if the consequences are mostly just broken http connections. Glad to volunteer my time of this!

**Comment by nluaces** [comment]
> Aside from leaving shells in inconvenient states, we are probably liable to be leaving whatever transactions we're performing in limbo in some places: even if the consequences are mostly just broken http connections. 

@c-kruse are you thinking in a bigger scope than this particular issue? I mean: have you spotted more similar scenarios not related with the spinner? 

> Glad to volunteer my time of this!
Thank you! 
I would like to collaborate on this too, but in case you want to start right away, feel free to do it!
