### ISSUE TITLE
Add owner reference to custom resources associated with a site

### ISSUE THREAD

**Issue by nluaces** [skupperproject/skupper#1630]
**Is your feature request related to a problem? Please describe.**
After deleting a site created with the CLI, the related resources (listeners, connectors) are still present in the namespace.

**Describe the solution you'd like**
Those custom resources need to have as the owner reference the site resource.

**Comment by grs** [comment]
Those are user supplied resources, so I don't think skupper should alter them to add owner references. The user can of course do that if desired.

**Comment by nluaces** [comment]
closing as it not going to be necessary to implement this.
