### ISSUE TITLE
[v2] CLI should allow to create listeners/connectors without having any site available.

### ISSUE THREAD

**Issue by nluaces** [skupperproject/skupper#1632]
**Is your feature request related to a problem? Please describe.**
When using the CLI, it is not possible to create listeners/connectors if there is no site created in the same namespace.

**Describe the solution that was requested**
The listener/connector create commands should not check if there is a site available.

**Comment by lynnemorrison** [comment]
code complete waiting on this PR to be merged
https://github.com/skupperproject/skupper/pull/1563
