### ISSUE TITLE
Remove httpConnector and httpListener references as they have been dropped from the router

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#1702]
**Describe the bug**
A recent router PR has been merged removing http adaptors:
https://github.com/skupperproject/skupper-router/pull/1617

We need Skupper V2 to get rid of them as well as config-sync and router logs are now
filled with errors querying http related entities.

**How To Reproduce**
Run a Skupper v2 deployment using skupper-router:main.

**Expected behavior**
No more errors on both components.

**Environment details**
 - Skupper V2
 - skupper-router:main

**Comment by grs** [comment]
Fixed by #1706
