### ISSUE TITLE
[v2] Listener Bindings invalid with single-stack IPV6 Cluster

### ISSUE THREAD

**Issue by c-kruse** [skupperproject/skupper#1806]
**Describe the bug**
Listeners do not work on single-stack IPv6 clusters. I think that is because they are hard coded to bind to `0.0.0.0`.

**How To Reproduce**
Follow kind docs to stand up an ipv6 only cluster. https://kind.sigs.k8s.io/docs/user/configuration/#networking
Try to replicate hello world.

**Expected behavior**
ehrm, it works? Maybe always binding `[::]` is the right answer all of the time? Can't say I've spent much time on this subject.

**Comment by grs** [comment]
Using [::] doesn't work with only ipv4. @kgiusti @astitcher is there anything we can bind on that would match all interfaces whether ipv4 or ipv6 for tcpListeners?

**Comment by grs** [comment]
Replying to myself, I believe the host should not be set at all. That is what happens for the listener elements (as compared with tcpListener elements) in the router config.
