### ISSUE TITLE
Implement cost option for connector

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper#22]

**Comment by ajssmith** [comment]
@grs I checked current by doing the following:

 ./skupper connect ~/sd/public1.yaml --cost 20

and observed in the qdrouterd.conf  that the config gets set accordingly:

connector {
    name: conn1-connector
    host: skupper-inter-router-skupper.apps.ansmith-van11.rhmw-integrations.net
    port: 443
    role: inter-router
    cost: 20
    sslProfile: conn1-profile
}

Is there any additional implementation that you had identified in order to support the cost option?

**Comment by grs** [comment]
No, that looks fine we can close the issue.
