### ISSUE TITLE
Feature request:  Cost argument for skupper connect

### ISSUE THREAD

**Issue by ted-ross** [skupperproject/skupper#221]
Consider adding an optional --cost switch to the skupper connect command.  The default value is 1.  If supplied (valid entries are natural numbers), the cost would be applied to the inter-router connection being created.  This is not valid for edge-to-interior connections.

The benefit of this feature is that users could create redundant topologies with a preference for one path over another.  For example, inter-continental connections could be given a higher cost than regions that are closer together.  Similarly, inter-provider connections might be given higher costs than inter-zone connections within a single provider.

**Comment by grs** [comment]
Implemented
