### ISSUE TITLE
A logs subcommand

### ISSUE THREAD

**Issue by ssorj** [skupperproject/skupper#223]
I'm not confident this is a good idea, but I'd like to consider a simplified entrypoint for getting logs from the Skupper infrastructure (router, proxies, proxy controller).  Where the status command gives you point-in-time information, the logs command would give you the sequence of events.  This would be helpful for next-level-of-detail debugging.

To keep the sizes down when needed, it should support the --limit option.

**Comment by nluaces** [comment]
Closing this ticket due inactivity. Feel free to reopen if the issue still exists.
