### ISSUE TITLE
Enable skupper cli autocomplete?

### ISSUE THREAD

**Issue by nicob87** [skupperproject/skupper#228]
Evaluate if we want to, and how to enable skupper cli autocomplete when pressing tab.

I thing cobra  command already has some support for that:
```
//ValidArgs is list of all valid non-flag arguments that are accepted in bash completions
ValidArgs []string
```

**Comment by ajssmith** [comment]
@nicob87 did your PR close this issue? Could you link it?

**Comment by nicob87** [comment]
Done in linked PR
