### ISSUE TITLE
Unable to deploy cockroach DB using Skupper version 0.3.1

### ISSUE THREAD

**Issue by cjireland** [skupperproject/skupper#255]
Hi, 

Following the example from @alexsotob (Twitter) on YouTube: https://youtu.be/1ud04d_5xMQ, I was unable to create the CRDB cluster. 

The exposure of the statefulset in the second cluster does not bring all the Kubernetes nodes to ready (1/1) and CockroachDB is unable to join the cluster from the nodes on the other cluster:

I200914 12:19:50.032858 31 server/server.go:1520  [n?] no stores bootstrapped and --join flag specified, awaiting init command or join with an already initialized node.
W200914 12:19:50.055258 101 gossip/gossip.go:1296  [n?] invalid bootstrap address: &{typ:tcp addr:cockroachdb-g1-0.cockroachdb-internal-g1:26257}, lookup cockroachdb-g1-0.cockroachdb-internal-g1 on 10.67.240.10:53: no such host
W200914 12:19:50.071472 101 gossip/gossip.go:1296  [n?] invalid bootstrap address: &{typ:tcp addr:cockroachdb-g1-1.cockroachdb-internal-g1:26257}, lookup cockroachdb-g1-1.cockroachdb-internal-g1 on 10.67.240.10:53: no such host
W200914 12:19:50.092867 101 gossip/gossip.go:1296  [n?] invalid bootstrap address: &{typ:tcp addr:cockroachdb-g1-2.cockroachdb-internal-g1:26257}, lookup cockroachdb-g1-2.cockroachdb-internal-g1 on 10.67.240.10:53: no such host

The problem is very easy to reproduce using the example YAML from Alex's YouTube video.

I downloaded Skupper version 0.2.0 and retried the example from Alex and it does work.

It seems that with 0.3.1 (the recommended download version on your docs site) the address resolution is not working.

Skupper is an absolutely brilliant product so it would be great if this can be resolved.

**Comment by grs** [comment]
Thanks for raising this @cjireland, will look into it and resolve.

**Comment by grs** [comment]
@cjireland this is now fixed in 0.3.2, and the image for the site-controller is tagged also as 0.3 (you may need to change the image pull policy to pick the image up if you already have the old version on your cluster). Thanks again for raising the issue!

**Comment by cjireland** [comment]
Great, thanks!
