### ISSUE TITLE
Implement console server

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper#28]
Parity to skupper-cli metrics and events handling

**Comment by ajssmith** [comment]
Should Include:
- Add skupper site id to qdr conf, via env
- oath-proxy support via transport, controller containers
- controller env
- service sync origin via site id

**Comment by grs** [comment]
@ajssmith I don't think we actually have the console being served and metrics provided yet, do we? (I.e. I think per the description above, this is not yet complete?)

**Comment by grs** [comment]
And to be clear I think to complete it we should do so with the revised data plane. At this stage it doesn't seem worth replicating what the old node.js controller does directly only to have to reimplement again for the envisaged data-plane. 

My point is simply we need some open item to recognise that there is still some work here (not to dump that work on you!).

**Comment by ajssmith** [comment]
Yes you are correct we need an issue to track as this PR was the setup for the subsequent controller/data plane work to ensue. I agree that the work should be targeted in the context of the new data plan implementation. The implication is that with current plan the 0.3 release will not be to parity with 0.2 release with regard to metrics. 

If we decide otherwise, I would be game to take a pass at replicating the node.js implementation. for the short term. Something to discuss.

**Comment by grs** [comment]
I think we can proceed with the emulated data-plane, i.e. we should target the anticipated interface, even before the actual data-plane work is finished. Much like we are doing in PR#50.
