### ISSUE TITLE
cannot configure all namespaces in a cluster for skupper

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#290]
When I try to set this up:

```kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/master/cmd/site-controller/deploy-watch-all-ns.yaml```

I get

```
clusterrole.rbac.authorization.k8s.io/skupper-site-controller unchanged
clusterrolebinding.rbac.authorization.k8s.io/skupper-site-controller unchanged
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/skupperproject/skupper/master/cmd/site-controller/deploy-watch-all-ns.yaml": namespaces "skupper-site-controller" not found
Error from server (NotFound): error when creating "https://raw.githubusercontent.com/skupperproject/skupper/master/cmd/site-controller/deploy-watch-all-ns.yaml": namespaces "skupper-site-controller" not found
```

cc @ajssmith as discussed

**Comment by ajssmith** [comment]
The deploy-watch-all-ns.yaml declares a service account and deployment for the namespace 'skupper-site-controller'. If the namespace does not exist, the error you observed will occur.

The user will need to create this namespace or alternatively modify the .yaml file to specify a different namespace that they created.

Apologize for not detailing this step. We should add this to the documentation.

**Comment by ajssmith** [comment]
@pwright can we close this or is there a doc issue we should track?

**Comment by ajssmith** [comment]
Please re-open if there is an issue
