### ISSUE TITLE
Skupper controller's DATA endpoint failing temporarily

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#295]
I have found an issue with Skupper controller's `/DATA` endpoint, after modifying
annotated protocol (`skupper.io/proxy`) for exposed services and deployments.

After switching the protocol to/from to http/tcp (and vice-versa), I noticed that the
`/DATA` endpoint becomes irresponsible for a few seconds from both namespaces
involved in my test. See the output below:

```
Retrieving services DATA from: public-annotated-1
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 09 Oct 2020 20:53:11 GMT
Content-Length: 79
```

```
Retrieving services DATA from: private-annotated-1
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 09 Oct 2020 20:53:16 GMT
Content-Length: 79
```

After a few seconds, I see that the service is responding properly again
and it returns a valid JSON.

**Comment by grs** [comment]
You don't have the content for those responses do you? (That would hopefully have an error message. The error should also be logged by the service controller pod)

**Comment by fgiorgetti** [comment]
I just got a bad response here, this time with a body:

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 20 Oct 2020 13:10:49 GMT
Content-Length: 54

parse error: Invalid numeric literal at line 1, column 6
```

**Comment by fgiorgetti** [comment]
@ajssmith I am still seeing it with the released images, but no longer when using a fresh controller image.
Once a new controller image is released, I believe this issue can be closed.

**Comment by ajssmith** [comment]
Please re-open if issue is observed again with 0.5.0 +
