### ISSUE TITLE
Skupper proxy image environment variable using duplicated names

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#297]
There are two environment variables being used to refer to the proxy image.
Some pieces of the code refer to it using: `PROXY_IMAGE` and in other places
we see it using `SKUPPER_PROXY_IMAGE`. We need to keep only one and get
rid of the duplicate.

Based on service and site controller image environment variables, probably the
`PROXY_IMAGE` might be the more appropriate choice.

**Comment by grs** [comment]
Note that https://github.com/skupperproject/skupper/pull/284 will now eliminate the need for the proxy image entirely as the router image will be used in its place.

**Comment by fgiorgetti** [comment]
Alright, so maybe we can wait for it and then once it is in the master branch, we can
close this issue (after verifying no other dups exist).

**Comment by grs** [comment]
No longer relevant now separate proxy image has been eliminated
