### ISSUE TITLE
Investigate 0.4 vs 0.3 compatibility.

### ISSUE THREAD

**Issue by mgoulish** [skupperproject/skupper#306]
Find out what will break if we try to mix version 0.4 with version 0.3 Skupper instances.

**Comment by Kampe** [comment]
is 0.4 slated for release soon?

**Comment by mgoulish** [comment]
Can't connect from v4 to v3.   Opening new issue.

**Comment by ajssmith** [comment]
Addressed by https://github.com/skupperproject/skupper/pull/374
