### ISSUE TITLE
Can't connect from v4 to v3.

### ISSUE THREAD

**Issue by mgoulish** [skupperproject/skupper#329]
Repro:

# Create namespace n1 and make a token in it,
# using Skupper Version 3.

kubectl create namespace n1
/usr/bin/kubectl config set-context --current --namespace=n1
/home/mick/skupper/skupper init                             # This is version 3.
/home/mick/skupper/skupper connection-token n1-secret.yaml  # This is version 3.

# Create namespace n2 using Skupper Version 3,
# and connect to n1 from it.

kubectl create namespace n2
/usr/bin/kubectl config set-context --current --namespace=n2
/home/mick/skupper-1/skupper init                    # This is version 4.
/home/mick/skupper-1/skupper connect n1-secret.yaml  # This is version 4.

Result:
Error: Failed to create connection: Can't check secret ownership: 'Can't find secret origin.'

**Comment by mgoulish** [comment]
Ah. Of course -- it's my 'generated-by' annotation that I added...
Looking for a way around it...

**Comment by ajssmith** [comment]
you can tale a look at:

https://groups.google.com/g/skupper/c/rZwIQyhZ2Lk/m/k5Kt-NVmBAAJ

**Comment by ajssmith** [comment]
Version check added to 0.5.0
