### ISSUE TITLE
Feature Request: Configurable Log Level Via Site Controller

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#332]
Hello!

This may or may not be a solved problem and just not documented somewhere, but the ability to be able to set the log level for skupper would be very useful.  

Our use-case requires our edge sites being connected via LTE radio, and skupper is our number one culprit of excessive logs due to it's nature, pumping up hundreds of thousands of logs hourly. While that's fantastic in a cloud setting potentially, we have data caps of 20GB/month and skupper can chew through this *very* easily. 

for more information, we currently create the skupper connection via the skupper-site-controller - having a log level option in the configmap would be awesome.

**Comment by Kampe** [comment]
Ah just noticed there's https://github.com/skupperproject/skupper/issues/69 which is a similar request

**Comment by grs** [comment]
I think this issue is specific enough and useful as is. Do you know which container(s) were the biggest problem?

**Comment by ted-ross** [comment]
Hi Nick,

Which component is generating the logs that you are concerned about?

-Ted

**Comment by Kampe** [comment]
it's the edge router in particular that is very chatty

**Comment by grs** [comment]
@Kampe Just to confirm for the router log, are there lots of errors logged? Or are the bulk of the logs info level? (Is there any one pattern there seems to be lots of)

**Comment by Kampe** [comment]
Entirely all info level logs with the notable exception of some node unhandled promise rejection warnings and a few ProtocolError: Close already received.

**Comment by grs** [comment]
Should be fixed by https://github.com/skupperproject/skupper/commit/c58f5e81cd2994136ba5fc61cd24e486f6f5cb19

**Comment by Kampe** [comment]
Most excellent, thank you! Will roll the new changes soon :)
