### ISSUE TITLE
v4 can't connect to v3 console

### ISSUE THREAD

**Issue by mgoulish** [skupperproject/skupper#338]
Make namespace n1.
Start v3 skupper in it.
Make a connection token.

Make namespace n2.
Start v4 skupper in it.
Connect to namespace n1.
( This will only work after you have applied PR 331.)

In n2 do "skupper status".
It prints out the URL for the web console.
In your browser, go there.

See this:
 ` JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 5 of the JSON data`

**Comment by ajssmith** [comment]
Ultimately addressed by #374
