### ISSUE TITLE
Feature Request: expose console service only internally, not over loadbalancer

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper#343]
when installing skupper with the console, the console service creates its own external IP to expose the UI.  For many this may be overkill as internal tools such as this are usually managed via `kubectl port-forward` - an option to not create a loadbalancer would be much appreciated!

**Comment by kungfuchicken** [comment]
+1

**Comment by grs** [comment]
Available from 0.5.1

**Comment by Kampe** [comment]
Excellent! Which setting in the configmap sets this option? I don't see any new options added in the example

Thanks!

**Comment by grs** [comment]
The option name is `console-ingress`, valid values are 'none' to not expose outside the cluster at all, 'loadbalancer' to make the service type LoadBalancer or (on openshift only) `route` to create a route for it. The default is to use whatever the `ingress` option is set to.
