### ISSUE TITLE
skupper console times out

### ISSUE THREAD

**Issue by hguerrero** [skupperproject/skupper#348]
When checking the console, it loses connection to the controller

![image](https://user-images.githubusercontent.com/1001939/102412831-02e99580-3fc2-11eb-96af-7f3489bb872a.png)

However info from `/DATA` is correct

```json
{
    "sites": [
        {
            "site_name": "azure",
            "site_id": "218dc1ab-ba41-4c9c-b9ce-986aacb9d01d",
            "connected": [],
            "namespace": "azure",
            "url": "52.151.225.245",
            "edge": false
        },
        {
            "site_name": "local",
            "site_id": "03815489-81a4-492e-97a0-68470ff2df58",
            "connected": [
                "218dc1ab-ba41-4c9c-b9ce-986aacb9d01d"
            ],
            "namespace": "local",
            "url": "",
            "edge": true
        }
    ],
    "services": [
        {
            "address": "hello-world-backend",
            "protocol": "tcp",
            "targets": [
                {
                    "name": "172.17.0.8",
                    "target": "hello-world-backend",
                    "site_id": "03815489-81a4-492e-97a0-68470ff2df58"
                }
            ]
        }
    ]
}
```

**Comment by hguerrero** [comment]
Looks like the timeout occurs when I expose the `hello-world-deployment`, if I remove it then I can connect to the console again.

**Comment by ErnieAllen** [comment]
commit 624ae60c4f5c9c91388f9b1cc83af1f5e44bc4be in the repository skupperproject/gilligan fixes this problem.
I'll leave this issue open until we get external confirmation that the fix is good.

**Comment by ajssmith** [comment]
I ran with above commit and did not encounter a time out. 

Worked for both:
expose
service create, service bind sequence
