### ISSUE TITLE
skupper autocomplete namespaces

### ISSUE THREAD

**Issue by nicob87** [skupperproject/skupper#367]
Similar to how kubectl autocompletes namespaces, the same may be done for skupper.
Ideally we will enable this feature for autocompleting available namespaces, and it could be possible to enable it for resouces like "--target <tab> <tab> (and autocomplete with available resources of the specified type.

**Comment by fgiorgetti** [comment]
@ajssmith, @grs @nicob87 should we close this one in favor of the broader one #574 ?

**Comment by grs** [comment]
yes, makes sense
