### ISSUE TITLE
How do I disable console?

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#406]
By default, skupper now provisions a console.
However, the only related cli option is `--enable-console`

@gsim should that now be flipped to `--disable-console`?

**Comment by grs** [comment]
@pwright The intention is that you can do --enable-console=false (similar to e.g. --enable-service-sync=false). However that is broken at present, I'll commit a fix shortly.

**Comment by pwright** [comment]
@gsim still feel that `enable-console=false` sounds like a hangover from when it wasn't enabled by default. This is not a priority, but even `console=false` would be better syntax for a system where it's enabled by default, so leaving open for the next cli review ;)

**Comment by ajssmith** [comment]
Fixed in 0.5.0 release
