### ISSUE TITLE
What identity is being referred to?

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#407]
`skupper token create secret.yaml --name NOTSKUPPER`

cli help says
```
      --name string   Provide a specific identity as which connecting skupper installation will be authenticated (default "skupper")
```
what use case does this address? should i use the same value for all sites in a network?

**Comment by grs** [comment]
It is the identity you want the site(s) connecting with that token to show up as in e.g. qdstat -c output. Generally it is an internal detail, but by specifying e.g. a unique site identifier and using a separate token for each site, you could get more data out if needed.

**Comment by ajssmith** [comment]
Please re-open if additional explanation needed
