### ISSUE TITLE
Update to use go 1.16

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#420]
Use go 1.16 and probably need to do some clean up on `go.mod` with `go mod tidy`.
The benefit is that `go build` and `go test` should not affect `go.mod` and `go.sum`.

**Comment by fgiorgetti** [comment]
Another improvement that can benefit from this update, is to use `go:embed` in order to define
the `client.Version` value in a text file that gets linked automatically at build time.

**Comment by grs** [comment]
Is a text file better than taking it from git? One of the benefits of git is that it will be different for every commit.

**Comment by fgiorgetti** [comment]
That's true. Version coming from git tag or commit id is easier and requires less intervention.
A better thing to use this would be the autocomplete shell script, in fact.
