### ISSUE TITLE
Console credentials are in different secret

### ISSUE THREAD

**Issue by hguerrero** [skupperproject/skupper#428]
When initializing skupper with default config you get a message to access the credential of the users in `skupper-users` however the secret name is `skupper-console-users` 

![image](https://user-images.githubusercontent.com/1001939/110369006-bf7a5280-8017-11eb-8085-302b281cb660.png)

**Comment by grs** [comment]
Should be fixed already in https://github.com/skupperproject/skupper/commit/07fe8242219c1776b8dd0ab9fd3baa7529d8e51e (will be part of 0.5).

**Comment by ajssmith** [comment]
Fixed in 0.5.0 release
