### ISSUE TITLE
Skupper console shows dummy data after a disconnection

### ISSUE THREAD

**Issue by hguerrero** [skupperproject/skupper#432]
When loading the console after a site disconnects, the console showed dummy data and graphs for a moment, until the correct information was displayed.

**Comment by grs** [comment]
This is https://github.com/skupperproject/gilligan/issues/7 which appears to be fixed by https://github.com/skupperproject/gilligan/commit/4552316d991082fed1e247dbe43cf858dfa3778c , so should be resolved for upcoming 0.5.0

**Comment by ajssmith** [comment]
fixed in 0.5.0 release
