### ISSUE TITLE
console link on docker desktop

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#436]
Docker desktop now offers an easy way to start a k8s instance.
As part of recent improvements to the cli, the `status` option now presents a link to the console, however on this k8s instance, the link presented is localhost:8080. 

This is probably a restriction of the k8s instance, but noting here as it might be confusing to some users.

**Comment by grs** [comment]
I assume that doesn't work?

What does `kubectl get services` show?

**Comment by pwright** [comment]
```
% kubectl get services
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                           AGE
skupper-controller   LoadBalancer   10.109.231.124   localhost     8080:31232/TCP                    79m
skupper-internal     LoadBalancer   10.101.74.12     localhost     55671:31029/TCP,45671:30094/TCP   79m
skupper-messaging    ClusterIP      10.111.221.202   <none>        5671/TCP                          79m
```

**Comment by pwright** [comment]
BTW localhost:8080 works now, maybe i just didn't wait long enough.

I created another site in a separate namespace (east) and that reports 
```
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)               AGE
skupper-controller   ClusterIP   10.110.155.86   <none>        8080/TCP              84m
skupper-internal     ClusterIP   10.101.88.102   <none>        55671/TCP,45671/TCP   84m
skupper-messaging    ClusterIP   10.101.144.70   <none>        5671/TCP              84m

```

no console url offered after `status` so I think i can close this? everything works as expected.
