### ISSUE TITLE
Enabling router console is not creating the route properly on OpenShift

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#450]
When initializing skupper using `--enable-router-console` on an OpenShift cluster, the route
is not being created.

Looking at the [router_create.go](https://github.com/skupperproject/skupper/blob/f33108d5adbdf73cfc79dfa40b192efc5336a763/client/router_create.go#L724) code it does not seem to be creating the route name accordingly as well.

**Comment by ajssmith** [comment]
Introduced with pull/201
