### ISSUE TITLE
Router console is not configured with SASL authentication when using internal console auth

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#457]
When `--enable-router-console` is used along with `--console-auth=internal`, the SASL configuration is
not being defined at the router config and so it is unable to authenticate (but it sets `authenticatePeer = true`).

**Comment by grs** [comment]
It seems to work ok for me. (The username must be qualified with @skupper-router though).

**Comment by fgiorgetti** [comment]
My mistake. Probably my environment was dirty. I started a new one and it is really working just fine.
Thanks for looking into Gordon!
