### ISSUE TITLE
Statefulset for proxies not being recreated after network outage

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#486]
I noticed that after a network outage, the Skupper network was restablished and the
services recreated. But I had a headless service as well, which got recreated properly,
but the statefulset for the proxies did not.

**Comment by ajssmith** [comment]
Would it be possible to attach the skupper debug dump? It might provide some insight.

**Comment by fgiorgetti** [comment]
Here they are.
[skupper-cockroachdb-private.dump.tar.gz](https://github.com/skupperproject/skupper/files/6480453/skupper-cockroachdb-private.dump.tar.gz)
[skupper-cockroachdb-public.dump.tar.gz](https://github.com/skupperproject/skupper/files/6480454/skupper-cockroachdb-public.dump.tar.gz)

**Comment by grs** [comment]
I attempted to simulate a network failure by scaling the skupper router to 0. However the statefulsets got recreated as expected after scaling back to 1. (I setup three sites a->b->c, with the target exposed in c, and scaled down the b router; both a and b recovered as expected).

The dumps don't show anything obvious. The events recorded probably need to be made a bit more useful for headless services. There are certainly no errors. The service definitions are correct in both sites.

**Comment by ajssmith** [comment]
@fgiorgetti are you ok if we close this and re-open if it returns persistently?

**Comment by fgiorgetti** [comment]
Sure stuff.
