### ISSUE TITLE
Multiple ports

### ISSUE THREAD

**Issue by OriolOMM** [skupperproject/skupper#491]
Hi,

I'm trying to expose a deployment that have a container that listens to multiple ports. How I should do this?

Regards

**Comment by grs** [comment]
At present you have to expose each port as a different service I'm afraid. Supporting multiple ports on the same service is not yet implemented (but is something we want eventually).

**Comment by OriolOMM** [comment]
Thanks,

So each port should have a different VAN address right?

**Comment by grs** [comment]
yes

**Comment by OriolOMM** [comment]
Thanks!
