### ISSUE TITLE
incorrect status when not logged into cluster

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#508]
```
$ skupper status
Skupper is not enabled in namespace 'pwright-test3'
```

then I realised I wasn't logged into cluster! 
After logging in (no other change)

```
$ skupper status

Skupper is enabled for namespace "pwright-test3" in interior mode. It is not connected to any other sites. It has 1 exposed service.
```

**Comment by grs** [comment]
When not logged in, do you have another active kubecontext? What did kuebctl get pods give you in that case?

**Comment by pwright** [comment]
I believe my login timed out, so will wait until I'm timed out again before `kubectl get pods`.
I do have other active contexts.

**Comment by pwright** [comment]
unable to reproduce
