### ISSUE TITLE
Nodeport ingress with claims

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#509]
When you initialize skupper using `--ingress nodeport` you must also provide the required flag: `--router-ingress-host`.
After doing so if you try to create a token claim (building skupper from master), it fails with:

```
$ skupper -n sk1 token create /tmp/sk1.yaml
Error: Failed to create connection token: Controller ingress host not defined, cannot use claims for nodeport without it.
```

Should `--controller-ingress-host` be required as well, or in case it is not provided, should skupper use the same value
provided through `--router-ingress-host`?

**Comment by grs** [comment]
There is a --ingress-host option that you can use if you want both controller and router to use the same value. Providing the controller host is considered optional as the site can operate without it. You have to specify `--token-type cert` in that case though. (Perhaps the error message could mention that, or mention that).

**Comment by fgiorgetti** [comment]
Nice. So I believe that simply adjusting the error message during `init`
should be enough.

Thank you.

Em qua., 14 de jul. de 2021 03:36, grs ***@***.***> escreveu:

**Comment by fgiorgetti** [comment]
@grs If I try to initialize my site using `--ingress-host` only, it still says that `--router-ingress-host` is required.
Do you think that, in such case when only the `--ingress-host` is specified, the `router-ingress-host` is still required?

**Comment by grs** [comment]
No, I agree it should be implied in that case.
