### ISSUE TITLE
what are links?

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#522]
consider the folllowing:

```
$ skupper link status
There are no links configured or active
$ skupper status
Skupper is enabled for namespace "west" in interior mode. It is connected to 1 other site. It has no exposed services.
```

While true, especially since we use the word 'connected', we suggest that link directionality (?) is only significant during creation, and that afterwards skupper doesn't worry about so much about direction (except for deletion, revocation, etc) 

I wonder if it would be better as 

```
$ skupper link status
There are no outgoing links configured or active
$ skupper status
Skupper is enabled for namespace "west" in interior mode. There is a link from 1 other site. It has no exposed services.
There are no outgoing links configured or active
```

Not totally convinced this is right, 'connected to X other sites' does have some value, but something to think about?

**Comment by grs** [comment]
Agree. "It is linked to 1 other site." would be better

**Comment by pwright** [comment]
Also notice that gateways appear in `skupper link status`, eg:

```
Link skupper-gateway-mylaptop not active
```

We don't describe the gateway as a link, so wondering if that should be changed?

**Comment by pwright** [comment]
noticed that if I delete the link associated with a gateway, that the gateway continues to operate as normal:

```
skupper link delete skupper-gateway-mylaptop
```
