### ISSUE TITLE
provide some way to control the kubernetes service type for skupper created services

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#53]
e.g. to allow a skupper service to be directly exposed as a loadbalancer type service.

(On openshift, this is less important as we can just do oc expose on the skupper service to create a route).

A key question is how this would affect service propagation. I don't think its should propagate the type to every site by default. One option might be that it only works locally. Another might be to explicitly list the sites for which the type applies.

**Comment by nluaces** [comment]
Closing this ticket due inactivity. Feel free to reopen if the issue still exists.
