### ISSUE TITLE
gateway delete not working

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#538]
```
$ skupper gateway delete mylaptop

$ skupper gateway status
No gateway definitions found
````

However, everything is still working

cc @ajssmith

**Comment by ajssmith** [comment]
The delete command takes the `--name` flag. I would have expected a command error from your input.

**Comment by pwright** [comment]
@ajssmith oops, copying my first attempt, what I actually issued was:

```
 skupper gateway delete --name mylaptop
```
it's all still in place, if that helps you debug?

**Comment by pwright** [comment]
cannot reproduce
