### ISSUE TITLE
Sample deployments descriptors for site-controller are referring to latest tag

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#545]
The sample YAML descriptors used to deploy site-controller are referring to the latest tag of the site-controller image:
```
deploy-watch-all-ns.yaml
deploy-watch-current-ns.yaml
```

I believe we need to either update them to 0.7 or update latest tag of both site and service controller images.

**Comment by grs** [comment]
I've updated the latest tag for both controllers.
