### ISSUE TITLE
create network policy to limit access to skupper services

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#562]
It would be good to have an option to have a network policy created by default when created a skupper site that limits access to the router (and therefore to exposed skupper services) to pods within that namespace.

**Comment by grs** [comment]
https://github.com/skupperproject/skupper/pull/563

**Comment by pwright** [comment]
@grs before you close this issue, could you explain the user story, my impression:

1. set up clusterA ns1 and create a token

2. On clusterB ns2:

skupper init --create-network-policy
skupper link create $HOME/secret.yaml
skupper expose deployment foo

I can access foo service from clusterA ns1, but on clusterB I can only access the foo service from ns2? 
What's the significance of 'current pods'? if I create a new pod in ns2, it cannot access foo?

**Comment by grs** [comment]
The main use of the network policy is to ensure that deployments (or other workloads) exposed to the skupper network from other sites, are not accesible by namespaces that are not themselves explicitly part of that skupper network.

So in your example, is the foo deployment was exposed on clusterA, then you don't want pods on clusterB that are not in ns2 able to access that service via the skupper router in ns2.

Not sure where the 'current pods' quote comes from, but it is done by labels so any new pod in ns2 can access foo.
