### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by 13567436138** [skupperproject/skupper#578]
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    12m                  default-scheduler  Successfully assigned istio/skupper-router-6bf4994ccb-s2bfq to 192.168.229.139
  Warning  FailedMount  12m                  kubelet            MountVolume.SetUp failed for volume "router-config" : configmap "skupper-internal" not found
  Warning  FailedMount  10m                  kubelet            Unable to attach or mount volumes: unmounted volumes=[skupper-site-server], unattached volumes=[router-config skupper-site-server kube-api-access-kfgnc skupper-local-server]: timed out waiting for the condition
  Warning  FailedMount  8m18s                kubelet            Unable to attach or mount volumes: unmounted volumes=[skupper-site-server], unattached volumes=[kube-api-access-kfgnc skupper-local-server router-config skupper-site-server]: timed out waiting for the condition
  Warning  FailedMount  6m4s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[skupper-site-server], unattached volumes=[skupper-local-server router-config skupper-site-server kube-api-access-kfgnc]: timed out waiting for the condition
  Warning  FailedMount  91s (x2 over 3m49s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[skupper-site-server], unattached volumes=[skupper-site-server kube-api-access-kfgnc skupper-local-server router-config]: timed out waiting for the condition
  Warning  FailedMount  19s (x14 over 12m)   kubelet            MountVolume.SetUp failed for volume "skupper-site-server" : secret "skupper-site-server" not found

[root@node01 ~]# skupper init -n istio
Secret already exists:  skupper-local-server
Secret already exists:  skupper-local-client
Secret already exists:  skupper-console-users
Waiting for LoadBalancer IP or hostname...
Error: Failed to get LoadBalancer IP or Hostname for service skupper-router

**Comment by grs** [comment]
'Failed to get LoadBalancer IP or Hostname for service skupper-router' most likely means that your cluster is not configured to create loadbalancer services. You can use NodePort instead by specifying `--ingress nodeport --ingress-host host-that-reaches-nodes` (other modes at present are openshift routes and nginx ingress)

Note that you need to run `skupper delete` before trying to run init again.

**Comment by 13567436138** [comment]
host-that-reaches-nodes  what should this value be?
