### ISSUE TITLE
Dynamic load balancing example

### ISSUE THREAD

**Issue by redblade** [skupperproject/skupper#581]
Hi all,
not sure where to open this issue.

About "Dynamic load balancing" mentioned in https://skupper.io/docs/overview/routing.html, could you point me to an example I could use to use such feature? I am using an on-prem test Kubernetes, not Openshift.
From the description, it seems Skupper uses cluster metrics to send the request to those with spare capacity using "costs". 
Would it be also possible to manually change such "costs" in order to take the traffic decisions into a separate service?

Thanks in advance

**Comment by grs** [comment]
The 'cost' is defined when linking one site to another. To change the cost you have to delete and recreate the link. The cost applies to all traffic and cannot be scoped to a specific service at this time.

(There is a desire to add the ability to do weighted routing of service traffic to different targets but that is not yet implemented),

**Comment by redblade** [comment]
thanks grs for the quick comment, I am closing this issue. I hope Skupper will support weighted routing of services soon
