### ISSUE TITLE
Skupper CLI allows the creation of links with used claims (then fails)

### ISSUE THREAD

**Issue by hguerrero** [skupperproject/skupper#583]
When creating a link, if you use a claim that has already been use (uses=1) you can create the link and it is configured, but the link status is failed:

`skupper link create tmp/token.yaml --name ts`

produces:

```
Site configured to link to https://claims-hybrid-cloud-demo.apps.shared-na46.openshift.opentlc.com:443/ff4d17ba-1fb0-11ec-8420-acde48001122 (name=ts)
```

but then when issuing `skupper link status`

We get:

```
Link ts not active (Failed to redeem claim: No such claim)
```

The create command should validate first the claim and reject the link creation.

**Comment by fgiorgetti** [comment]
Fixed by #1415
