### ISSUE TITLE
[gateway] Do not occupy port 5672

### ISSUE THREAD

**Issue by ssorj** [skupperproject/skupper#616]
This regularly trips me up.

Ports are a shared resource at host scope.  On a Linux system, 5672 is effectively reserved for system installed messaging servers.  Installing the router will try to use port 5672 and fail if it cannot.

By contrast, the use of qdrouterd for the gateway is purely an implementation detail.  It has no business taking port 5672.

**Comment by ajssmith** [comment]
Resolved by #659
