### ISSUE TITLE
Report errors if an incompatible site is detected in the network

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#621]
We need to improve logging or the output of `skupper status` and/or the upcoming `skupper network`
to report errors if incompatible sites connect to the network.

**Comment by fgiorgetti** [comment]
Part 1 of this issue would be to include it as part of the `get sites` command, returning something like:

```
$ kubectl -n sk1 exec deploy/skupper-service-controller -- get sites
ID                                   NAME EDGE  VERSION                                               NAMESPACE URL            CONNECTED TO
3438c102-6f3c-4056-afa9-39d3ed1bbd76 sk1  false 0.8.3                                                 sk1       10.111.235.167 
726e8874-635b-43e9-b6a9-e56035fcbbc9 sk2  false 0.7.0 (incompatible - minimum version required 0.8.0) sk2       10.104.60.10   3438c102-6f3c-4056-afa9-39d3ed1bbd76
```

Thinking about other places to include it, I would say `skupper network` makes more sense to me.

**Comment by fgiorgetti** [comment]
@nluaces a small change that helps with this issue has been done through https://github.com/skupperproject/skupper/pull/654.
But I believe this might be a nice addition to be part of the `skupper network` command as well. WDYT?

**Comment by nluaces** [comment]
@fgiorgetti I agree with you, the information of version incompatibility could provide valuable information about the status of the skupper network.

**Comment by fgiorgetti** [comment]
Last incompatible version is too old (0.8.0).
I would say this is no longer applicable.
