### ISSUE TITLE
When I deploy to a local kubernetes cluster, how do I configure and use the local image registry?

### ISSUE THREAD

**Issue by lzj47010** [skupperproject/skupper#627]
![image](https://user-images.githubusercontent.com/50096566/139802525-bb0b325e-2133-4c8e-a391-9963256300ff.png)
When I tried to configure Env, the result didn't take effect

**Comment by grs** [comment]
How are you deploying?

**Comment by lzj47010** [comment]
Thanks, I using site controller. I used the wrong environment before,now it's success.
  If possible, it is recommended to https://skupper.io/docs/declarative/tutorial.html Add relevant environmental instructions to the page. Thank you again
