### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by ws-prive** [skupperproject/skupper#633]
Hi,

I am looking for help how to configure Skupper with Prometheus/Thanos. When I look at the Prometheus example and run it, it remains on Waiting for LoadBalancer IP or hostname. How must I setup the config to get this working, do I need an ingress on the public hosts? I am running on-premise clusters.

The second question is about the link, I do see an url in there, is internet connectivity required?

Thanks!

**Comment by grs** [comment]
To connect two 'sites' (i.e. namespaces on clusters), one cluster needs to be accessible to the the other. The --ingress option will control how a skupper site is exposed to others. It can use a loadbalancer service, an openshift route, a nodeport, an nginx ingress (if ssl-passthrough is enabled on the nginx ingress controller), or as of 0.8.1, a Contour HttpProxy. If you don't want to use any of these you can specify --ingress none. However in that case, though the site will still be able to create a link out to  external skupper sites if they have a valid ingress,  other sites will not be able to link to it. (The direction of the link places no limit on the direction of traffic).

**Comment by ws-prive** [comment]
Ok, thanks. I do have a central cluster with Thanos running and a decentral cluster with Prometheus and a Thanos sidecar. The central cluster with Thanos needs to connect to the Prometheus/Thanos sidecar on the decentral cluster. Present, I do have the service of Prometheus/Thanos sidecar on the decentral cluster on nodeport, but Ingress is also possible. What is you advise to set it up correctly?

**Comment by grs** [comment]
I would suggest having the decentral cluster link to the central cluster, then you can expose the thanos sidecar as a service that the central cluster's thanos can use to connect to it. On the decentral cluster you can use --ingress none.  Do you have either nginx or contour setup for ingress on the central cluster already? Does the central cluster support services of type LoadBalancer?

**Comment by ws-prive** [comment]
Hi @grs, 

Thanks. All the clusters (on-premise) do not have the option to have a service of type lb. Present I do have installed the latest nginx-ingress on the central cluster, but not configured it for Skupper. How does a config for nginx for Skupper look like?

**Comment by grs** [comment]
You need to edit the nginx-ingress-controller deployment to add --enable-ssl-passthrough in the command line arguments passed through to the container. Once you have done that, you just need to skupper init --ingress=nginx-ingress-v1. If you have dns setup to point at that cluster, you can specify the domain via --ingess-host. Otherwise skupper will try to determine the ip or host from the status of the ingress it creates.

**Comment by ws-prive** [comment]
Thanks again. Present, the nginx-ingress-controller is used for other inbound traffic, just not on the namespace where thanos is running, so I can not set the enable-ssl-passthrough on the controller level. However, via annotations I can set it on an nginx-ingress object, but I am unaware how to set it up for Skupper. Do you have an example?

**Comment by grs** [comment]
Skupper will automatically create the ingress object with the appropriate annotation. However that annotation will have no effect if ssl-passthrough is not enabled in the controller (note that doing so will not make all existing ingresses use passthrough, it will only enable use of the pass through annotation).

**Comment by ws-prive** [comment]
Hi @grs,

Clear, I have added the ssl-passthrough to the nginx-ingress and restarted the container:

![image](https://user-images.githubusercontent.com/59507751/140951102-9781f7b3-bad1-4c9a-b33f-26cf79764e02.png)

Than I executed the script below
```
NAMESPACE=monitoring
CENTRAL_CLUSTER=kind-central
DECENTRAL_CLUSTER=kind-decentral

# CENTRAL
kubectl config use-context ${CENTRAL_CLUSTER}
kubectl create ns ${NAMESPACE}
skupper init --ingress nginx-ingress-v1 --ingress-host test-thanos.internal.xxxxxxx.com -n ${NAMESPACE}
skupper token create ./secret.yaml -n ${NAMESPACE}

# DECENTRAL
kubectl config use-context ${DECENTRAL_CLUSTER}
kubectl create ns ${NAMESPACE}
skupper init --ingress none -n ${NAMESPACE}
skupper link create ./secret.yaml -n ${NAMESPACE}

```

All fine, but when I take a look via 
```
skupper link status -n ${NAMESPACE}
```
it states: 

```
Link link1 not active
```
I am not sure if this is correct or not, can you please take a look at this?

Thanks again!

**Comment by grs** [comment]
That looks like the right steps. Are you using skupper 0.8.1?

One way to debug is to curl the host names in the skupper ingress with -v (and -k) to see what is terminating the ssl. Also, what are the annotations on the link1 secret in the DECENTRAL namespace?

**Comment by ws-prive** [comment]
Hello @grs again,

Thanks for your patience and help!

The version:
![image](https://user-images.githubusercontent.com/59507751/140962902-70620cd1-4ae8-4e20-ab2a-c35ed38f4702.png)

About the curl, do I need to do this from a pod inside the k8s cluster? This because the stated domains are not in my dns.

The internal.xxxxxx.com was a wildcard subdomain, so I changed the dns to use just one name for the thanos central cluster. When I repeat the commands with the new domain I do get:

```
Link link1 not active (Failed to redeem claim: Post https://claims.monitoring.central-thanos.xxxxxxxx.com:443/a8d4320e-417b-11ec-b218-0cd292ff57e4?site-version=0.8.1: dial tcp: lookup claims.monitoring.central-thanos.xxxxxxxx.com on 10.96.0.10:53: no such host)
```
Any clue?

**Comment by grs** [comment]
Try without the --ingress-host (do skupper delete first, before init again).

**Comment by grs** [comment]
Try without the --ingress-host (do skupper delete first, before init again).

**Comment by ws-prive** [comment]
Hi @grs ,

Done, but failing, it is also remaining on localhost (I think):

```
Link link1 not active (Failed to redeem claim: Post https://claims.monitoring.localhost:443/80fb7098-4180-11ec-a4b6-0cd292ff57e4?site-version=0.8.1: dial tcp [::1]:443: connect: connection refused)
```

**Comment by grs** [comment]
Do you know the IP by which the ingress on the central cluster is accessed? Is that accessible from a pod on the decentral cluster?

**Comment by ws-prive** [comment]
Hi @grs ,

I hope I understand you correctly, I have deployed a testpod in the monitoring namespace on the decentral cluster en done a ping to the ip address of the host where the central cluster is running on and I do get a response. FYI, both clusters do have the same ip ranges for the pods, is that a problem? The endpoints on both clusters do contain the same IP addresses.

**Comment by grs** [comment]
Ok, thats good. Now what happens if you curl that ip address from the testpod, curl -k -v https:<your-ip-address>

**Comment by ws-prive** [comment]
Hi @grs 

This is what I get
```
curl -k -v https://172.18.0.2
* Expire in 0 ms for 6 (transfer 0x559445e21fb0)
*   Trying 172.18.0.2...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559445e21fb0)
* Connected to 172.18.0.2 (172.18.0.2) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Nov  9 14:57:44 2021 GMT
*  expire date: Nov  9 14:57:44 2022 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x559445e21fb0)
> GET / HTTP/2
> Host: 172.18.0.2
> User-Agent: curl/7.64.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< date: Tue, 09 Nov 2021 18:40:43 GMT
< content-type: text/html
< content-length: 146
< strict-transport-security: max-age=15724800; includeSubDomains
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host 172.18.0.2 left intact
```

**Comment by grs** [comment]
Ok, that looks good. Try now re init-ing skupper with --ingress-host 172.18.0.2.nip.io

**Comment by ws-prive** [comment]
Hi @grs ,

Done, unfortunally, the link is not active:

```
Link link1 not active
```

**Comment by grs** [comment]
What do you get for `curl -k -v https://claims.monitoring.172.18.0.2.nip.io/foo`?

**Comment by ws-prive** [comment]
![image](https://user-images.githubusercontent.com/59507751/141003561-fa9f1701-05b3-4eb5-8bda-29031ee0d220.png)

**Comment by ted-ross** [comment]
The address that you are using for the central cluster (172.18.0.2) is a
private, non-routable address.  You need to use the cluster's public IP
address for connectivity to be established.

-Ted

**Comment by ws-prive** [comment]
Hi @ted-ross 

Thanks, but I do have 2 on-premise clusters without any public ip addresses.

**Comment by ted-ross** [comment]
Ok.  If 172.18.x.x is your on-premise subnet, spanning both clusters, then
you are correct, this is not the problem.

**Comment by ws-prive** [comment]
@ted-ross, thanks for your help, appreciate it!

**Comment by grs** [comment]
were the two attempts abive from the same location? they seem to give different results:
 
```
curl -k -v https://172.18.0.2
* Expire in 0 ms for 6 (transfer 0x559445e21fb0)
*   Trying 172.18.0.2...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559445e21fb0)
* Connected to 172.18.0.2 (172.18.0.2) port 443 (#0)
* 
```

versus https://user-images.githubusercontent.com/59507751/141003561-fa9f1701-05b3-4eb5-8bda-29031ee0d220.png

Same ip and port but one connects and one does not.

**Comment by ws-prive** [comment]
Hello @grs 

Yes, they were.

**Comment by grs** [comment]
How repeatable are those results?

**Comment by ws-prive** [comment]
Hello @grs,

I had to remove the testclusters from yesterday, they were broken. I have setup 2 new kind clusters, but when using this:
```
NAMESPACE=monitoring
CENTRAL_CLUSTER=kind-central
kubectl config use-context ${CENTRAL_CLUSTER}
kubectl create ns ${NAMESPACE}
skupper init --ingress nginx-ingress-v1 --ingress-host central-thanos.xxxxxx.com -n ${NAMESPACE}
```
I do get this error, so I am lost why:
```
Secret already exists:  skupper-local-server
Secret already exists:  skupper-local-client
Secret already exists:  skupper-site-server
Secret already exists:  skupper-console-users
Error: the server could not find the requested resource
```

**Comment by grs** [comment]
That implies skupper already exists in the namespace. Try `skupper status` and `skupper version` and then `skupper delete` and you should be able to run the init again without error.

**Comment by ws-prive** [comment]
Hi @grs,

It was a new cluster. I have tun skupper delete -n monitoring, the output of skupper status -n monitoring is:
```
Skupper is not enabled in namespace 'monitoring'
```
Then I rerun the skupper init --ingress nginx-ingress-v1 --ingress-host central-thanos.xxxxxx.com -n monitoring, the output is:
```
Error: the server could not find the requested resource
```
I have no clue why this is happening

**Comment by ws-prive** [comment]
@grs, when I execute the command in the default namespace with skupper init --ingress nginx-ingress-v1 --ingress-host central-thanos.xxxxxx.com , the output is:
```
Waiting for LoadBalancer IP or hostname...
Error: Failed to get LoadBalancer IP or Hostname for service skupper-router
```

**Comment by ws-prive** [comment]
I have removed the kind clusters and setup vm's instead and used the exact same setup and then it is working. It looks like a kind related issue. @grs, thanks for your help.
