### ISSUE TITLE
CA validity change

### ISSUE THREAD

**Issue by ws-prive** [skupperproject/skupper#635]
Hello,

Is it possible to change the CA validity from the default 5 years to something else?

**Comment by grs** [comment]
Not through skupper yet. There will be more flexibility around CA and certs in future releases. You can also create the CA yourself (e.g. with cert-manager) and as long as it is in a secret with the right name (using kubernetes naming conventions for tls certs) skupper will use that.

**Comment by ws-prive** [comment]
Hello @grs 

Thanks, but what if there are more tls-secrets in the namespace, how does skupper know which to use?

**Comment by grs** [comment]
It relies on the name.

**Comment by ws-prive** [comment]
Hello @grs, do you have an example how to use cert-manager and which name it should use?

**Comment by ws-prive** [comment]
@grs, thanks
