### ISSUE TITLE
Add a CLI command to show service controller events

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#648]
It would be useful if we could run `get events` from the CLI, like:
`skupper events` or `skupper debug events`.

**Comment by fgiorgetti** [comment]
What if we add all the respective `get` commands as part of the `debug` command?
In example:
```
skupper debug events
skupper debug servicecheck
skupper debug services
skupper debug sites
skupper debug version
```
Any thoughts @ajssmith @grs ?

**Comment by grs** [comment]
I definitely agree with the aim. Not entirely sure about the best way to expose through the cli. Ultimately I would like all the 'informational' subcommands to use the service controller http api via an exec of the get command, e.g. skupper status, skupper link status, skupper service status, etc). This will likely involve some evolution of the get command and the oaths it calls as well.

Having a way to expose what is there at present in the short term does seem useful though. Using 'debug' is not a bad choice. Another option could be 'xp'  or 'experimental' to more clearly indicate that the exact form may change.

**Comment by nluaces** [comment]
Solved in https://github.com/skupperproject/skupper/pull/695
