### ISSUE TITLE
Is there a way to deploy only one instance of skupper to proxy all the services from different namespaces in one cluster?

### ISSUE THREAD

**Issue by SataQiu** [skupperproject/skupper#652]
Hi, Is there a way to deploy only one instance of `skupper` to proxy all the services from different namespaces in one cluster??

If I wanted to proxy services from different namespaces cross clusters, deploying skupper for each namespace seemed a waste of resources. 

Can we support `skupper-service-controller` and `skupper-router` work cluster-wide?

**Comment by grs** [comment]
Not at present

**Comment by SataQiu** [comment]
Thanks @grs

**Comment by grs** [comment]
That is only the site controller. It will then create a skupper router and skupper service controller for each namespace that requests them. At present the service controller can only configure the router to route to workloads in that same namespace.

**Comment by grs** [comment]
> Hi @grs is this still the case ? I'm having issue with skupper installed in one namespace not watching annotation apply to a service in an other namespace to automatically expose it, can you provide insight ?

v1.x does not support monitoring for annotated resources outside the namespace.

**Comment by waldner** [comment]
> v1.x does not support monitoring for annotated resources outside the namespace.

Sorry for jumping in here...I see there are already some 2.x tags, is there some documentation on major changes and new features that will be in v2?

**Comment by grs** [comment]
@waldner also see https://skupper.io/v2 & https://skupperproject.github.io/refdog/
