### ISSUE TITLE
How to create services, the endpoints of which exist in multiple clusters

### ISSUE THREAD

**Issue by hhyasdf** [skupperproject/skupper#657]
Hello, guys.

I have two clusters named `cluster-A` and `cluster-B`, and two deployment with the same name of `test-deploy` exist in both the two clusters.

And I'm wondering if Skupper supports creating a service with a name of `test/test-svc` in both `cluster-A` and `cluster-B`, while pods in `cluster-A` can access the `test-deploy` deployment pods (in both `cluster-A` and `cluster-B`) via `test/test-svc` service.

Thanks for any help.

**Comment by grs** [comment]
Yes, run `skupper -n test export deployment test-deploy --address test-svc` in both clusters

**Comment by hhyasdf** [comment]
It helps a lot. Thanks @grs .
