### ISSUE TITLE
skupper status crashes during initial setup when following the tutorial

### ISSUE THREAD

**Issue by IlyaM** [skupperproject/skupper#669]
Hey,

I tried to configure skupper on my local kind based Kubernetes cluster and I was just following instructions on https://skupper.io/docs/declarative/tutorial.html . In this instruction on step 2 it is suggested to run 'skupper status' to verify the installation and I tried to do exactly this. This, unfortunately, seems to result in skupper crashing with the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13392b9]

goroutine 1 [running]:
github.com/skupperproject/skupper/client.(*VanClient).RouterInspectNamespace(0xc000221700, 0x18707c0, 0xc00003e078, 0xc0002fb60c, 0x4, 0x1, 0xc00010b2c0, 0xc0000e1ca0)
        /home/circleci/project/client/router_inspect.go:94 +0x1e9
github.com/skupperproject/skupper/client.(*VanClient).RouterInspect(0xc000221700, 0x18707c0, 0xc00003e078, 0xc000317008, 0x4, 0x3)
        /home/circleci/project/client/router_inspect.go:73 +0x50
main.NewCmdStatus.func1(0xc0002e9340, 0x2320788, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/cmd/skupper/skupper.go:578 +0x74
github.com/spf13/cobra.(*Command).execute(0xc0002e9340, 0x2320788, 0x0, 0x0, 0xc0002e9340, 0x2320788)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00031edc0, 0x0, 0x0, 0xc0000ae058)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        /home/circleci/project/cmd/skupper/skupper.go:1708 +0x2d
```

I'm using the latest version of skupper - this is the output of skupper version:

```
client version                 0.8.1
transport version              not-found
controller version             not-found
```

**Comment by grs** [comment]
Could you try with the latest client 0.8.5 to see if the same issue occurs there?

**Comment by IlyaM** [comment]
Just tried to download 0.8.5 and yes, it is crashing with the same error:

```
ilya@LAPTOP-BTSC7RI1:~/tmp$ skupper status
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1337379]

goroutine 1 [running]:
github.com/skupperproject/skupper/client.(*VanClient).RouterInspectNamespace(0xc000251640, 0x186f240, 0xc0000c2000, 0xc00032b57c, 0x4, 0x1815321, 0x1ffffffffffffff, 0xc0000f1ca0)
        /home/circleci/project/client/router_inspect.go:106 +0x379
github.com/skupperproject/skupper/client.(*VanClient).RouterInspect(0xc000251640, 0x186f240, 0xc0000c2000, 0xc000348bf8, 0x4, 0x3)
        /home/circleci/project/client/router_inspect.go:76 +0x50
main.NewCmdStatus.func1(0xc00031b340, 0x231e808, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/project/cmd/skupper/skupper.go:579 +0x74
github.com/spf13/cobra.(*Command).execute(0xc00031b340, 0x231e808, 0x0, 0x0, 0xc00031b340, 0x231e808)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00034edc0, 0x0, 0x0, 0xc0000a8058)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
main.main()
        /home/circleci/project/cmd/skupper/skupper.go:1709 +0x2d
ilya@LAPTOP-BTSC7RI1:~/tmp$ skupper version
client version                 0.8.5
transport version              not-found
controller version             not-found
```

By the way, in the public documentation 0.8.1 is shown as the latest version (see https://skupper.io/releases/index.html), you have to go to github to find 0.8.5.

**Comment by grs** [comment]
What does `kubectl get cm` show? Did you update the site-controller deployment to 0.8.5 as well?

**Comment by grs** [comment]
Thanks for pointing out the issue with latest release on the doc site!

**Comment by IlyaM** [comment]
> Did you update the site-controller deployment to 0.8.5 as well?

Not at first. I  used manifest linked from the tutorial which I now see to be pointing to a much older version 0.3. In step 2 of the tutorial it says to deploy the controller using the command:

`kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/0.3/cmd/site-controller/deploy-watch-current-ns.yaml`

I just tried to run after recreating the test namespace

`kubectl apply -f https://raw.githubusercontent.com/skupperproject/skupper/0.8.5/cmd/site-controller/deploy-watch-current-ns.yaml`

 and now skipper status no longer crashes and shows the expected message. So it looks like the problem was a combination of incompatibility of different versions of the skupper CLI command and the controller and outdated links in the tutorial.

**Comment by grs** [comment]
Thanks for pointing out those stale versions. I've raised specific issues to track them.
