### ISSUE TITLE
Design and implement general error and status reporting.

### ISSUE THREAD

**Issue by mgoulish** [skupperproject/skupper#69]
* A general approach that will work with the Skupper CLI, the Skupper Library, and the declarative implementation.

    * Consistent across the code base.

    * Be able to control what information it gathers and what it reports.

    * Be able to control verbosity at any time during execution.   ( I.e. set verbose mode only during init and delete.)

      * This replaces issues 19 and 34.

**Comment by ajssmith** [comment]
Closing as exceptions and logging treatment is generally treated in a consistent fashion.

New issues should be created for specific enhancements.
