### ISSUE TITLE
Service creation may fail silently when executed right after policy change that allows it.

### ISSUE THREAD

**Issue by hash-d** [skupperproject/skupper#728]
# How to reproduce

On a script, pipeline or program (not manually, so that the steps occur as close one to the other as possible):
- Give `AllowedServices` permission on a namespace for any services (`"*"`)
- Immediatelly after that, issue `skupper service create hello-world-frontend 8080 --mapping http`
- Check that the service was created (`skupper service status`)

Run that combination several times.  In-between each cycle, remove the policy that allows the services and ensure that the services were removed.

# Expected behavior

The `skupper service create` command should either fail because of missing policies (and then the `skupper service status` command return empty), or succeed in such a way that `skupper service status` would return the created service.

# Actual behavior

The actual test was exactly as described above, but on two namespaces at the same time; in one of them, the policy was actually removed, while on the other the target namespace was removed  from the policy and later reinstated (the policy was edited).

The `skupper service create` command returned a successul response 100% of the time.  However, it not always created the services.  On each test, it failed at a different iteration:

- Test 1 - 1st
- Test 2 - 6st
- Test 3 - 10th
- Test 4 - 4th
- Test 5 - 12th

The low numbers on repetitions till failure indicates that it this situation should occur fairly frequently (whenever policy creation and service creation happen one right after the other).  Actually, the test was created because I saw it several times a day while performing other, unrelated testing.

**Comment by hash-d** [comment]
```
$ for a in $(grep -l allow-policy--and--immediatelly-create-service test*); do echo $a; sed -n '/allow-policy--and--immediatelly-create-service/h; /not available/ {x; p; q}' $a; echo; done

test-2022-04-19T11:41:59-1201033
=== CONT  TestPolicies/tests/testServicePolicyTransitions/allow-policy--and--immediatelly-create-service/add-policy--create-service/parallel/service-create-backend

test-2022-04-19T11:44:10-1201815
=== CONT  TestPolicies/tests/testServicePolicyTransitions/allow-policy--and--immediatelly-create-service/add-policy--create-service#06/parallel/service-create-backend

test-2022-04-19T11:49:40-1203466
=== CONT  TestPolicies/tests/testServicePolicyTransitions/allow-policy--and--immediatelly-create-service/add-policy--create-service#10/parallel/service-create-backend

test-2022-04-19T11:56:20-1216090
=== CONT  TestPolicies/tests/testServicePolicyTransitions/allow-policy--and--immediatelly-create-service/add-policy--create-service#04/parallel/service-create-backend

test-2022-04-19T12:01:17-1217441
=== CONT  TestPolicies/tests/testServicePolicyTransitions/allow-policy--and--immediatelly-create-service/add-policy--create-service#12/parallel/service-create-backend
```

**Comment by hash-d** [comment]
When swapping the removal methods between the namespaces (actual removal of policy or removal of target namespace within the policy), the behavior changed, and was consistent throughout the three runs.

Before, the test was always failing on the simple service get check via `cluster.VanClient.KubeClient.CoreV1().Services(cluster.Namespace).Get()` that is executed by `service.CreateTester.Run()` itself, and always on the backend service/private namespace only (which was the one whose policy was being removed altogether).

After the swap, both `service create` report success, but then the `service status` reports only the backend service/private namespace on both lists (ie, running `service status` from private and from public).

With that, even though the actual behavior was different between the tests, it affected always the namespace whose policy was removed altogether.  The one where the namespace was removed from the policy, and the policy allowed to continue existing, was not affected.

**Comment by hash-d** [comment]
On the tests above (with the swapped policy removal methods), the tests failed on the 9th, 14th and 4th iterations.

**Comment by hash-d** [comment]
While developing another test, I put a sleep of 4s between adding the policy and creating the services.  Still, it failed with this error on the 6th cycle.  I have increased the sleep for 8s and started the test again.

However, 4s looked pretty high, already.  Perhaps this is not a timing thing, after all, but instead a bad interaction between the two policy changes?

**Comment by hash-d** [comment]
Running that other test with 8s between adding policy and creating services worked fine on the first run with 100 cycles.  

However, the second run was killed after 120 minutes, because the issue described on this ticket occurred five times, on cycles 25, 31, 35, 52, 54.  54 was the latest cycle, unfinished, because of the timeout.

Yet, when running 400 cycles with an increased sleep to 10 seconds, it worked successfully in 3h40min.  I cannot tell whether the difference is due to size of sleep or due to computer utilization (the test is running on my own computer, and the 400 cycles were run off hours, when I was not using it).

**Comment by hash-d** [comment]
Some recent change (perhaps #738?) seems to have made this occur more often.

After experiencing this situation a few times, I re-ran the test with 100 cycles, and the error occurred on 60 of those cycles:

```
$ sed -n '/allow-policy--and--immediatelly-create-service/h; /attempt: 100/ {x; p}' test-2022-04-27T18:18:40-2563260  | grep immediatelly | sort | uniq | wc -l
60
```

For now, I'll change the tests to add a sleep after this type of policy changes, and report.

**Comment by hash-d** [comment]
Adding a 5s delay after each policy change made the 100 cycles pass without any errors.  I haven't tested other delays.

**Comment by hash-d** [comment]
Policy regression worked fine when setting a five-second interval between policy changes and the execution of the following command.  It failed in several tests, however, when no such wait period was used.

That's probably to be expected, as the change increases the likelihood that a policy change will take a bit longer to be recognized by the system.

The tests will be updated to check for the expected policy change, instead of a static wait.  However, #747 has some open questions to be addressed; the changes will be made only once those are addressed.

**Comment by hash-d** [comment]
On the retest with swapped policy removal method and 100 cycles, there were 36 failures, of which 2 were unexpected:

After the frontend namespace had its policy removed, and the backend namespace had its policy edited to remove the namespace from the list, the service `hello-world-backend` started to show as not authorized _on both namespaces_, whereas it should have been removed from both:

```
2022/05/05 14:16:58 Validating 'skupper service status' - attempt 7
2022/05/05 14:16:58 Validating 'skupper service status' - attempt 7
2022/05/05 14:16:58 Running: skupper --namespace public-policy-namespaces-1 --kubeconfig /home/dhashimo/D/git/RedHat/kubeconfig/crc.kubeconfig service status
2022/05/05 14:16:58 Running: skupper --namespace public-policy-namespaces-2 --kubeconfig /home/dhashimo/D/git/RedHat/kubeconfig/crc.kubeconfig service status
STDOUT:
Services exposed through Skupper:
╰─ hello-world-backend (http port 8080) - not authorized

STDERR:

Error: <nil>
2022/05/05 14:16:58 error executing service status command: expected:
.*hello-world-backend \(http port 8080\)
Absent: true
found:
Services exposed through Skupper:
╰─ hello-world-backend (http port 8080) - not authorized
```

The attempts were limited to a count of 10, so perhaps the policy would have been stabilized later.  In any case, these 10 attempts took a full minute to complete.  I'll re-run the test without the attempt limitation (the test will still be limited to 10 minutes, though), and report what happens.

**Comment by fgiorgetti** [comment]
@hash-d The policy fix is working correctly. This latest behavior that has been observed
is actually a general skupper issue related with concurrency on service interface creation/removal.

I am going to write down a unit test to reproduce that issue and propose a solution.
