### ISSUE TITLE
Provide a way to prevent kubernetes service creation in namespace where target worklfow is bound

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#729]
For more control over how services are exposed across a skupper network, it would be useful to have a mechanism by which a workload in a given site can be exposed (i.e. one or more egress created), without creating a corresponding kubernetes service )i.e. have no ingress for the skupper service at that site).

**Comment by grs** [comment]
An initial thought on this, with a view to a simple change, would be to add a ```ingressDisabled``` field to ```types.ServiceInterface``` struct, and to have the controller check that flag prior to creating (or updating) the kubernetes service.

**Comment by cmunford73** [comment]
A couple of thoughts:
-  Do you mean that we would need an option in the cli for 'skupper service create' and 'skupper expose', as opposed to 'skupper service expose'?  I think this is a good way to expose this to the user.  
- One thing to consider is service sync, and that this should only take effect in the site where the deployment is bound, and not propagate to the remote sites.  It should remain possible for other sites to expose the service, while the local site (site with the bound deployment) remains exposed.  
- Given that one can currently expose a service in a remote site without bouncing the service in the local bound site (ie unexposing/re-exposing the service), it would be good to allow this new cli option to be toggled (ie. command issued with and without the option) to control local exposure without having to 'skupper service delete + create' or 'skupper unexpose + expose' to change the option, which would be service affecting in all sites that are exposed.

**Comment by grs** [comment]
I agree it should only apply to the local site. Service sync, if enabled, should not propagate this new field.

The heart of the change is a change to the type used in `skupper-services`. The additional cli option and annotation is just the interface to that model.

I think to alter the value on an existing skupper service definition, we would want a new subcommand, e.g. `skupper service update` (or perhaps update-xxx, for every xxx we wish to be editable).

**Comment by grs** [comment]
This will be redundant in v2, where the ingress- and egress- bidings are controlled through separate resources.
