### ISSUE TITLE
enable-tls with unsupported protocol

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#761]
enable-tls is only supported with http2, however when I set up the hello-world example and issue the following command, I don't get a warning

```
skupper expose deployment hello-world-backend --port 8081 --protocol tcp --enable-tls
```

```
skupper version
client version                 1.0.0
transport version              quay.io/skupper/skupper-router:2.0.1 (sha256:5f08ae90af0a)
controller version             quay.io/skupper/service-controller:1.0.0 (sha256:85f4dab48dcd)
config-sync version            quay.io/skupper/config-sync:1.0.0 (sha256:c16f8b171840)

```

**Comment by pwright** [comment]
cc @nluaces

**Comment by pwright** [comment]
When I modify the hello-world example to use tls it returns the error as expected
```
Error: Unable to create skupper service: The TLS support is only available for http2
```
investigating the exact circumstances when the error is not displayed

**Comment by pwright** [comment]
Ok,  If you try to use tls on tcp, you get the error as expected. But if you expose a tcp service, then run the expose command again, with tls, you don't get the error, eg
```
skupper expose deployment/hello-world-backend --port 8080 
deployment hello-world-backend exposed as hello-world-backend
skupper expose deployment/hello-world-backend --port 8080 --protocol tcp --enable-tls
deployment hello-world-backend exposed as hello-world-backend

```
My guess is that this is not related to tls, but maybe there's a generic issue relating to exposing the same object twice? wdyt @nluaces

**Comment by nluaces** [comment]
@pwright thank you for reporting this! The error comes from a validator of the service, I will check if this validation is not executed when exposing the same service. Thanks!
