### ISSUE TITLE
Failure of the `skupper network status` command

### ISSUE THREAD

**Issue by ted-ross** [skupperproject/skupper#766]
I have a 4-node skupper network that has been running over the weekend.  I can run `skupper status` and get a correct result in about 6 seconds.  The `skupper network status` fails after a delay of 6.5 minutes.

```
ONPREM$ time skupper status
Skupper is enabled for namespace "new-demo" with site name "ONPREM" in interior mode. It is connected to 3 other sites (2 indirectly). It has 2 exposed services.
The site console url is:  https://10.111.145.29:8080
The credentials for internal console-auth mode are held in secret: 'skupper-console-users'

real	0m6.091s
user	0m0.062s
sys	0m0.017s
ONPREM$ time skupper network status
Unable to retrieve network information: temporarily unable to provide site information

real	6m28.709s
user	0m0.836s
sys	0m0.392s
```

**Comment by ted-ross** [comment]
Upon further examination, it appears that the network itself is not functioning correctly.  Some of the routers are unreachable via their 5671 port due to SSL failures.

**Comment by ted-ross** [comment]
Related:  https://github.com/skupperproject/skupper-router/issues/473

**Comment by nluaces** [comment]
Improvements for the command: 
- Retry strategy with a limit when calling the service-controller
- Show at least local configuration if the information provided by the service-controller is not available
- Add more granularity to the error messages (which sites are not available) if possible
- Show TCP local connections
