### ISSUE TITLE
Add skupper/cmd/site-controller README

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper#77]
This is the site-controller application so README should provide overview of operation and details/content for:

- site config maps
- token requests
- tokens for connect, etc.

**Comment by pwright** [comment]
@ajssmith Do we have any example ConfigMap(s) at this point?

**Comment by ajssmith** [comment]
apiVersion: v1
data:
  cluster-local: "false"
  console: "true"
  console-authentication: internal
  console-password: "barney"
  console-user: "rubble"
  edge: "false"
  name: skupp3r
  router-console: "true"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site

**Comment by ajssmith** [comment]
@pwright let me know if you have a question...
