### ISSUE TITLE
skupper-router deployment breaks due to no resources set in container template

### ISSUE THREAD

**Issue by OrangeMako** [skupperproject/skupper#773]
I have been trying to deploy skupper using the following guide: https://skupper.io/docs/declarative/tutorial.html

I am having a problem where the skupper-router deployment fails to deploy because the config-sync container template in the deployment does not specify CPU or memory requests/limits. Due to the use of quotas in the cluster this stops the pod from rolling out as expected. 

It looks like its just not been set at all on the container
https://github.com/skupperproject/skupper/blob/0231e4e8ed206946b353fbaf0d823c448bad0f2a/client/router_create.go#L53

Could we get a way to specify these resources in the skupper-site config map similar to the way its done for the other router and service controller?

**Comment by ajssmith** [comment]
Yes, the ability to set the quotas for resource limits is planned for the next release.
