### ISSUE TITLE
Skupper update does not re-write secrets

### ISSUE THREAD

**Issue by ted-ross** [skupperproject/skupper#791]
I picked up version 1.0.2 so I could use the fix to #785.  Running `skupper update` was successful in updating the router and the service controller, but the secrets (specifically skupper-local-client) were not re-generated.  Therefore, the bug in 1.0.1 remained in effect after the update to 1.0.2.

**Comment by nluaces** [comment]
The `skupper update`command is rewriting secrets only for versions less recent than skupper 0.5.0.
