### ISSUE TITLE
timeout for loadbalancer resolution should be configurable

### ISSUE THREAD

**Issue by grs** [skupperproject/skupper#807]
Invoking `skupper init` with the default loadbalancer option waits until the loadbalancer ip or host is available. At present it gives up after a hardcoded duration. We should make that waiting time configurable.

**Comment by burrsutter** [comment]
Ideally have this message "Waiting for LoadBalancer IP or hostname..." also say "Waiting 30 seconds for LoadBalancer IP or hostname..." or whatever the end-user's specified waiting interval is.  I believe skupper needs 2 IPs provisioned.
