### ISSUE TITLE
The link cost is not displayed anywhere

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#815]
The link cost information is being set correctly, but there is no easy way to see it.
It would be nice to display it as part of the console, as well as the `skupper network status` command.

**Comment by nluaces** [comment]
If we work on showing the link cost in the verbose mode of the link status command, it wouldn't be necessary to add it in the network status command, what do you think?

**Comment by fgiorgetti** [comment]
Sounds fair to me.

**Comment by nluaces** [comment]
It will be solved with the solution for #878
