### ISSUE TITLE
skupper revoke-access doesn't work as expected

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#826]
- What does `skupper revoke access` do?
	- After setting up the hello-world example, and setting context to `west`:
	- ```
	  bash-5.1$ skupper status
	  Skupper is enabled for namespace "west" in interior mode. It is connected to 1 other site. It has 1 exposed service.
	  There are no links configured or active
	  
	  bash-5.1$ skupper revoke-access
	  
	  bash-5.1$ skupper status
	  Skupper is enabled for namespace "west" in interior mode. It is not connected to any other sites. It has 1 exposed service.
	  ```
	- So, even tho there are no links from `west`, all links (in this case one link from `east`) are removed and exposed skupper services are orphaned.
	- Looking at the skupper status from `east`
	- ```
	  bash-5.1$ skupper status -n east
	  Skupper is enabled for namespace "east" in interior mode. It is not connected to any other sites. It has 1 exposed service.
	  ```
So far so good, however:

```
bash-5.1$ skupper token create ~/token.yaml
Token written to /home/user/token.yaml 
bash-5.1$ skupper link create ~/token.yaml -n east
Error: Failed to create link: Already connected to "05f8c38e-e8b6-4dc8-a9a0-1ead98461a61".
```
How can I undo `revoke access`?

**Comment by grs** [comment]
What does `skupper links status -n east` show? Delete any link there and try again?
