### ISSUE TITLE
Exposing a statefulset creates a proxy statefulset which reuses the application headless service

### ISSUE THREAD

**Issue by rmallam** [skupperproject/skupper#829]
**Problem statement:**

When a stateful set is exposed as a headless service using skupper, A new stateful set called appname-proxy gets created, but this stateful set reuses the service that is used by the application, This will basically create a problem when you try to access the pod using its identity. See example below.

Redis is deployed as a stateful set, which has a service called redis-headless  created, to be able to access each pod by its name.
$oc get sts
NAME                   READY   AGE
redis-master           1/1     71m
redis-replicas         3/3     71m

$oc get sts redis-master -o yaml
....
spec:
 ....
  **serviceName: redis-headless**
 ....

when i expose redis-master stateful set using skupper as a headless service using the below command a new stateful set called 
redis-headless-proxy  is created and it reuses **redis-headless**  service. Reusing this service name will make it not possible to access pod identity for the stateful set redis-headless-proxy. This will not really matter when we use plain text communication but if we enable end-to-end TLS between applications and if the application expects the certificate to match the hostname of the pod from which the request comes, it creates a problem.

**skupper expose statefulset redis-master  --headless** 

$oc get sts
NAME                   READY   AGE
redis-headless-proxy   1/1     63m
redis-master           1/1     71m
redis-replicas         3/3     71m

$oc get svc
NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)               AGE
redis-headless                          ClusterIP   None             <none>        6379/TCP              72m
redis-master                            ClusterIP   172.21.136.41    <none>        6379/TCP              72m
redis-replicas                          ClusterIP   172.21.241.50    <none>        6379/TCP              72m
skupper                                 ClusterIP   172.21.111.78    <none>        8080/TCP,8081/TCP     78m
skupper-router                          ClusterIP   172.21.131.250   <none>        55671/TCP,45671/TCP   78m
skupper-router-local                    ClusterIP   172.21.197.98    <none>        5671/TCP              78m

$oc get sts redis-headless-proxy -o yaml
spec:
 ..... 
  serviceName: redis-headless
......

ping responses from inside the cluster.
sh-5.0# ping redis-master-0.redis-headless.skupper-local.svc.cluster.local
PING redis-master-0.redis-headless.skupper-local.svc.cluster.local (10.1.0.11) 56(84) bytes of data.
64 bytes from redis-master-0.redis-headless.skupper-local.svc.cluster.local (10.1.0.11): icmp_seq=1 ttl=64 time=0.088 ms
64 bytes from redis-master-0.redis-headless.skupper-local.svc.cluster.local (10.1.0.11): icmp_seq=2 ttl=64 time=0.099 ms

--- redis-master-0.redis-headless.skupper-local.svc.cluster.local ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 62ms
rtt min/avg/max/mdev = 0.088/0.093/0.099/0.011 ms

sh-5.0# ping redis-headless-proxy-0.redis-headless.skupper-local.svc.cluster.local
ping: redis-headless-proxy-0.redis-headless.skupper-local.svc.cluster.local: Name or service not known

**Work around to  get this working**

I created a new service called **redis-headless-proxy** and updated the stateful set redis-headless-proxy to use the new service created. This will give the ability to get the pod identity for redis-headless-proxy pods.

$oc explain sts.spec.serviceName
KIND:     StatefulSet
VERSION:  apps/v1

FIELD:    serviceName <string>

DESCRIPTION:
     serviceName is the name of the service that governs this StatefulSet. This
     service must exist before the StatefulSet, and is responsible for the
     network identity of the set. Pods get DNS/hostnames that follow the
     pattern: pod-specific-string.serviceName.default.svc.cluster.local where
     "pod-specific-string" is managed by the StatefulSet controller.

**Comment by grs** [comment]
I agree that skupper should not reuse the original service in this context. As you point out, those serverside proxy pods are not intended to be addressable through DNS. By End-to-end TLS, do you mean re-encrypted by Skupper? (If it was compeletely end-to-end then skupper would not have any involvement in the handshaking). In general when using skupper the IP of the process invoking on a service will not be the client, but a skupper router. The current headless service implementation is a special case in that it does have pods that logical map one-to-one with the 'real' client pods. However it is conceivable that a future implementation would not have that characteristic.

As I understand it, your encrypted service is using the source IP of a request to reverse lookup a hostname, and then matching that against the certificate the client presents? Where are the valid hostnames specified? Would it not be possible to add skupper pods to taht (that would be an approach that would work for all skupper services, not just the current headless implementation).

**Comment by rmallam** [comment]
@grs When i meant End-To-End TLS, the application is deployed with TLS enabled and will communicate with other pods over TLS to form a quorum.  Though i used Redis as an example above, The usecase is mainly for Kafka implementation, 

We have Kafka brokers deployed as statefulsets in two different openshift clusters and and are exposed as a  headless service using skupper. 3 nodes of kakfa brokers are deployed on both sites and all 6 nodes will form a quorum together using skupper.  when the nodes from both the clusters try to communicate with each other, The communication is via the skupper proxy routers that are created.

For example: if kafka borker 1 on cluster 1  wants to communicate with Kakfa broker 1 on Cluster 2, I understand the communication path is as shown below. 

```mermaid
flowchart LR;
   cluster2Kafkabroker1-skupper-pod -->  cluster2Kafkabroker1-skupper-proxy-pod
  subgraph cluster2 ;
   cluster2Kafkabroker1-skupper-proxy-pod --> Cluster2kafkabroker1 ;
   end  
    subgraph cluster1 ;
    cluster1kafkabroker1 --> cluster2Kafkabroker1-skupper-pod;
   end
```
So when the requests originates from the Kakfa broker on one cluster to reach other kafka broker on other cluster, it passes through the skupper proxy pods thats are created to reach the other cluster. When the request reaches the kafka broker on the other cluster, The originator for that request will be the proxy pod created by stateful set when kakfa broker statefulset is exposed by skupper and this shares the service name with the application. 

Kafka brokers communicate on TLS, so when the request arrives, The kafka brokers checks if the certificates presented matches the hostnames of the originator. Ideally, the originator is the kafka broker on the other cluster and the certificates are created to match their hostnames but because we have skupper in between to enable cluster to cluster communication, The originator is now one of the skupper proxy pod and currently these proxy stateful sets that are created by skupper doest have a dedicated service name attached to them and they dont have their own identity making it hard to create certificates. 

I did a work around by pre-populating the proxy statefulset with a dedicated service name and then exposed the stateful set via skupper. This provides an identity to the pods which can be added to the certificate SAN's.

Hope this is clear. @ajssmith is also across this issue. He might be able to give some more insight here.

**Comment by grs** [comment]
Ok, understood. You just need the ability to resolve the IP of the pod connecting to kafka to a known, stable hostname that can be included in its certificate.

**Comment by rmallam** [comment]
yes thats correct, A stable hostname will help to include these hostnames in the certificate SAN,
