### ISSUE TITLE
Scaling up/down a Skupper exposed statefulset, triggers restart for all the skupper proxy pods

### ISSUE THREAD

**Issue by rmallam** [skupperproject/skupper#837]
When a statefulset is exposed via skupper, it creates proxy pods on the local and remote clusters and when the application stateful set is scaled up/down, All the skupper proxy pods gets recreated, impacting the application availability for that time.  I have tested this scenario with RabbitMQ and kafka, Both these apps will have to reestablish the quorum when there is a change in number of replicas.

Steps to reproduce: 

Deploy any statefulset with 2 replicas.

skupper expose stateful name --headless

Wait for all the proxy pods to be created on both local and remote clusters.

oc scale statefulset name --replicas=3

observe the proxy pods getting recreated.

**Comment by grs** [comment]
At present the skupper service controller is doing an update on the statefulset if the replicas change. If only the replicas differ then it should instead do a patch.

**Comment by grs** [comment]
@rmallam I can't reproduce the problem as you describe it. What I see when scaling up is that only the new pod is created.

```
               1/1     Running   0          113m
myservice2-proxy-1                            1/1     Running   0          113m
myservice2-proxy-2                            1/1     Running   0          23s
skupper-router-6bd5fb7fc9-t8v9q               2/2     Running   0          114m
skupper-service-controller-55ccdf7dbf-hmz4h   1/1     Running   0          114m
stateful-example-0                            1/1     Running   0          132m
stateful-example-1                            1/1     Running   0          132m
stateful-example-2                            1/1     Running   0          24s
```

and

```
                   READY   STATUS    RESTARTS   AGE
skupper-router-7f7458f45d-nmqvc               2/2     Running   0          3m18s
skupper-service-controller-77fcb89c7c-f47mt   1/1     Running   0          3m16s
stateful-example-0                            1/1     Running   0          2m43s
stateful-example-1                            1/1     Running   0          2m39s
stateful-example-2                            1/1     Running   0          105s
```

You can see from the times that the pods were not all recreated.

**Comment by rmallam** [comment]
@grs True, This is not happening anymore, I think it was happening for me because of old version of skupper that i was using and the proxy pods which get created on the remote cluster were not having the resources propagated. I updated to the latest and it works now. Thanks again,.
