### ISSUE TITLE
Service autodiscovery/autosync/autoexpose?

### ISSUE THREAD

**Issue by ondrejhlavacek** [skupperproject/skupper#846]
Is there a way I can set up skupper to expose pods/deployments automatically? We have a dedicated namespace with skupper and we have an external service that deploys workloads in to this namespace. It would be great if the external service did not need to know about skupper and just deploed a pod/deployment as usual.

**Comment by ted-ross** [comment]
A couple of thoughts come to mind:

1) Would it be difficult for your external service (or just the workload
descriptions) to use the annotations for Skupper exposure?  Or is this the
thing you are trying to avoid?

2) If the Skupper service-controller had a mode of operation whereby all
deployments are exposed unless explicitly annotated to not be exposed,
would this meet your requirements?

-Ted

**Comment by ondrejhlavacek** [comment]
The annotations are just fine, didn't know they existed. Thanks a lot, that answers my question :-)

**Comment by jiridanek** [comment]
https://groups.google.com/g/skupper/c/UXts2qif5RA/m/9pjvF6JxEQAJ
