### ISSUE TITLE
Router ports customization

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#847]
Ingress ports used by the skupper-router are statically defined today.
This would help in cases where users have a constrained range of allowed ports, e.g: 443.

**Comment by grs** [comment]
The ports actually exposed depends on the ingress option chosen. For openshift routes, contour http-proxy and ingress, it is currently already assumed to be 443. (With node-port it will be the assigned port. Only with loadbalancer will it be the actual ports the router is configured to listen on).

I agree that it would be useful to have an option that allows the port used for ingress and contour http-proxy to be altered in case the local setup does *not* use 443.

**Comment by fgiorgetti** [comment]
Closing as no longer applicable.
