### ISSUE TITLE
Service annotation to define only ingress into the VAN

### ISSUE THREAD

**Issue by fgiorgetti** [skupperproject/skupper#848]
We need some new annotation that would cause Skupper to define just the ingress to an existing VAN service.
This particular service will target the data plane.

This helps users that do not use service-sync to declare their whole service network manually through annotation.

**Comment by hash-d** [comment]
@fgiorgetti, @grs, can this be closed from #986?

**Comment by grs** [comment]
I believe so, yes. @fgiorgetti do you agree?
