### ISSUE TITLE
default to disable console when ingress is set to 'none'

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#856]
Many folks are running the 'private' part of their service network on clusters that don't have ingress, eg kind,minikube, microshift.

Typically they need to `skupper init --ingress none` to account for the environment

For these scenarios, it might be better if console is not enabled by default to avoid the scenario of `skupper status` returning a url that doesn't work
If they need a console, they can override this default

**Comment by grs** [comment]
By default, if ingress is none, the console will not be accessible outside of the cluster. It will also be secured by a randomly generated password.

I don't see `skupper status` showing a url in this case either (which I agree would be something to correct).

**Comment by pwright** [comment]
@grs  I think that's good enough
