### ISSUE TITLE
starting skupper with custom --site-name causes connecting links to fail

### ISSUE THREAD

**Issue by awm-achi** [skupperproject/skupper#863]
With a cloud server in namespace skupper, if I use 
```
skupper init --site-name test 
skupper token create <token>

```
then on a local cluster in namespace skupper, with command 
```
skupper init
skupper link create <token>
skupper link status 
```

returns Link link1 not active (Failed to redeem claim: No such claim)

**Comment by grs** [comment]
I don't think it is the --site-name option that is causing the issue. By default the token claims have a short life. Is it possible more than 10 minutes elapsed between creating the token and using it to create the link?

**Comment by aschi2** [comment]
I set up these namespaces and tested this problem specifically so token creation to link creation happened under a minute.

**Comment by awm-achi** [comment]
I create the token and immediately link it to the new site so token creation to link happens within 1 minute

**Comment by grs** [comment]
You always get that same error? (i.e. 'Failed to redeem claim: No such claim)')

**Comment by awm-achi** [comment]
Yes it's always the same

**Comment by awm-achi** [comment]
Has anyone else been able to try this? I can get it to work if I omit the --site-name and that's what we currently have running, but I can't seem to get the --site-name to work. Also if I try to edit it after the fact in the ui, it says successfully applied but the name doesn't actually change.

**Comment by grs** [comment]
I've tried it and it works fine for me.

The site-name doesn't affect the token issued or its use, so I can't see how that could be related. The error suggests that the claim is being used up (by default it can only be used once) or expired before that link creation. Is it possible the token being used in one case is stale?

The fact that changing the name after the site has been initialised is a known issue at present.

**Comment by awm-achi** [comment]
I tried again, and it still didn't work, but I was able to get it to work by setting uses to 2 during token creation. not sure what is staling/ using the token when uses is not increased but it's an easy enough workaround for me.

**Comment by grs** [comment]
That suggests that the token is being used twice.

**Comment by awm-achi** [comment]
I'm definitely only using it once, it's a deployment in it's own test namespace, and I'm running it all at once (with a context switch in between)
