### ISSUE TITLE
Trying to expose tcp server , But getting an openssl error

### ISSUE THREAD

**Issue by sathyap0104** [skupperproject/skupper#864]
Hi Team,
I have 2 cluster's one in cloud and another in local. 
I'm trying to expose local cluster Api service and link with the cluster in cloud.
i exposed the server and able to see it in the cloud cluster. but while trying to curl , It's throwing the below error.  
![Screenshot (15)](https://user-images.githubusercontent.com/57754665/187367500-4f0000ec-8000-41d8-8f64-b635a28337c2.png)
Any help is appreciated

**Comment by grs** [comment]
Is the service you are exposing using TLS? Did you specify port 443 when exposing through skupper? What does `skupper service status` show?

**Comment by sathyap0104** [comment]
hi @grs Thank you for the replay. I exposed it through  this command `skupper expose service kubernetes --address hotel1 --port 443` . and 'skupper service status' show's 
``` 
Services exposed through Skupper:
╰─ hotel1 (tcp port 443)
   ╰─ Targets:
      ╰─ kubernetes name=kubernetes 
```

**Comment by sathyap0104** [comment]
And the local cluster is of k3s and cloud one is gpc cluster. I'm trying to expose k3s cluster kubernetes k3s Api server

**Comment by grs** [comment]
I tried the same thing, albeit with different kubernetes distros, and it worked ok for me. However the / path gave a 403 without a valid authentication token.

Can you run curl with -v as well as -k? What do you see for that?
