### ISSUE TITLE
Arm64 support for the CLI

### ISSUE THREAD

**Issue by aureamunoz** [skupperproject/skupper#888]
Hello!
I have a Mac M1 and would like to install skupper, would it be possible to have the corresponding package? Currently it seems only amd is supported

Thank you in advance!

**Comment by ted-ross** [comment]
I assume we will also need companion issues to produce aarch64 images for skupper-router and config-sync.

**Comment by grs** [comment]
arm64 images is tracked by https://github.com/skupperproject/skupper/issues/884

**Comment by lucacalcaterra** [comment]
@grs @ted-ross at the moment can i use arm64 images ? On quay.io seems missing arm images

**Comment by grs** [comment]
No, we do not as yet have any arm64 images published.
