### ISSUE TITLE
skupper status reports incorrect connect info with edge mode

### ISSUE THREAD

**Issue by ajssmith** [skupperproject/skupper#90]
Observed while deploying skupper-example-mongodb-replica-set

Three router setup, 2 public (interior mode) and 1 private (edge mode)

Public2 connects to Public1
Private1 connects to Public1 and Public 2

From Public interiors 'skupper status' generates:
VanRouter is enabled for namespace '"skupper" in interior mode'. It is connected to 3 other sites (1 indirectly). It has no exposed services.

From Private edge 'skupper status' generates:
VanRouter is enabled for namespace '"skupper" in edge mode'. It is connected to 3 other sites (2 indirectly). It has no exposed services.

Expected result was that status returns: 'It is connected to 2 other sites'.

Changing Private deployment from edge to interior produced expected result.

QDR version 1.12.0

**Comment by ajssmith** [comment]
Thinking about it further, would correct status be: 'It is connected to 2 other sites (1 indirectly)' as there is only one active edge uplink?

Are there any rules adding connectors when in edge mode?

**Comment by grs** [comment]
There can only be one active connector from an edge at one time.

The skupper-cli repo had this same issue and fixed it, possibly that was after work had begun on this one?

**Comment by grs** [comment]
Comment above from me is inaccurate. Should learn to read the issue :-(

**Comment by mgoulish** [comment]
Gordon - thanks for noticing redundant code -- all removed now -- same testing results as before.
Tests 1 through 4 good -- number 5 fails the same way.
