### ISSUE TITLE
skupper install fails if the route already exists

### ISSUE THREAD

**Issue by rmallam** [skupperproject/skupper#922]
Hi,

I am trying to install skupper with a custom host definition for skupper-inter-router route, So i pre created the route with the custom hostname but the skupper install fails with the error "route already exisits". Should we not fail the install in this scenario and use the existing route?

2022/10/19 02:55:29 Error initialising skupper:  Route skupper-inter-router already exists
E1019 02:55:29.381694       1 controller.go:167] Route skupper-inter-router already exists

Regards,
Rakesh

**Comment by grs** [comment]
Fixed in #921

**Comment by rmallam** [comment]
@grs  nice, thanks for the fix.
