### ISSUE TITLE
Flaky CI pipeline, needs tuning.

### ISSUE THREAD

**Issue by nicob87** [skupperproject/skupper#95]
https://app.circleci.com/pipelines/github/skupperproject/skupper/150/workflows/b39d9140-e1eb-4559-b13b-0f416b88713e/jobs/866
sometimes, probably due to variation in the VM bandwidth, The test fails, moreover the internet issue, probably the test can be fixed, to retry, or wait or something, in order the make it work always.

**Comment by nicob87** [comment]
To improve this, at least, the port forwarding must be implemented using the "client-go" api instead of calling the cli "kubectl port-forward" command:
Some doc about that:
https://github.com/kubernetes/client-go/issues/51
https://gianarb.it/blog/programmatically-kube-port-forward-in-go
https://github.com/gianarb/kube-port-forward/blob/master/main.go

**Comment by nicob87** [comment]
Without the port-forwarding here we have had the same error:
https://app.circleci.com/pipelines/github/skupperproject/skupper/266/workflows/15f31f26-1863-4c00-95b1-f0dff1228e6b/jobs/1319

Specifically doing:

```
conn, err := net.DialTCP("tcp", nil, tcpAddr)                                                                   
if err != nil {                                                                                                 
return fmt.Errorf("Dial failed: %s\n", err.Error())                                                     
}
```

With this information some resear may be done, it it makes sense probably just retrying the dialTCP attempt may be enough to fix this.



```

**Comment by grs** [comment]
It will take some time after the service is exposed for the router (or currently bridge-server) to actually configure the listener and start accepting connections. Retrying seem the right thing for now, we have talked about a way of determining when the service is actually ready (https://github.com/skupperproject/skupper/issues/163)
