### ISSUE TITLE
Grpc load balancing exposing cross namespace service

### ISSUE THREAD

**Issue by iagodvsantos** [skupperproject/skupper#950]
In order to expose an app located in a different namespace, one needs to create a service from the deployment, and only then Skupper can expose this service cross-site. However, it seems like Skupper doesn't properly handle GRPC load-balancing in this scenario - for instance, the load is not distributed among the new pods when the app scales up - even when the deployment is exposed through a headless service 🤔. Is it supposed to work like this or have I misconfigured something?

**Comment by grs** [comment]
You need to use http2 as the protocol when using skupper expose (or as the value from skupper.io/proxy if using annotations). That will cause the router to parse individual requests and route them seperately.

**Comment by iagodvsantos** [comment]
@grs I used http2 as protocol, the issue is that when exposing directly a deployment in the same namespace, it works just fine. However, when exposing a service located in another namespace it doesn't.

**Comment by grs** [comment]
Sorry, my mistake.

Can you run curl against port 8080 on the service controller (or the `skupper` service), with path /DATA? That will give some aggregated metrics that would help diagnose things further.

**Comment by iagodvsantos** [comment]
That's the output of `/DATA` endpoint @grs 

```
{
    "sites": [
        {
            "site_name": "operators",
            "site_id": "b41fbd8b-06d2-444b-a92b-5b03d9d934b5",
            "version": "1.1.1",
            "connected": [],
            "namespace": "operators",
            "edge": false,
            "gateway": false
        },
        {
            "site_name": "",
            "site_id": "332753ba-fc7e-4553-b845-8331fa596f06",
            "version": "1.1.1",
            "connected": [
                "b41fbd8b-06d2-444b-a92b-5b03d9d934b5"
            ],
            "namespace": "",
            "url": "",
            "edge": false,
            "gateway": false
        }
    ],
    "services": [
        {
            "address": "voting-svc",
            "protocol": "http2",
            "targets": [
                {
                    "name": "voting-svc.coletas",
                    "target": "voting-svc",
                    "site_id": "b41fbd8b-06d2-444b-a92b-5b03d9d934b5"
                },
                {
                    "name": "voting-svc.coletas",
                    "target": "voting-svc",
                    "site_id": "b41fbd8b-06d2-444b-a92b-5b03d9d934b5"
                }
            ],
            "requests_received": null,
            "requests_handled": [
                {
                    "site_id": "b41fbd8b-06d2-444b-a92b-5b03d9d934b5",
                    "by_server": {
                        "voting-d984b9cb4-zqmk5": {
                            "requests": 83401,
                            "bytes_in": 417005,
                            "bytes_out": 417005,
                            "details": {
                                "POST:200": 83401
                            },
                            "latency_max": 184
                        },
                        "voting-svc.coletas": {
                            "requests": 305469,
                            "bytes_in": 1527345,
                            "bytes_out": 1527345,
                            "details": {
                                "POST:200": 305469
                            },
                            "latency_max": 1191647
                        }
                    },
                    "by_originating_site": {
                        "332753ba-fc7e-4553-b845-8331fa596f06": {
                            "requests": 452881,
                            "bytes_in": 2264405,
                            "bytes_out": 2264405,
                            "details": {
                                "POST:200": 452881
                            },
                            "latency_max": 1191647
                        },
                        "56938b34-3c9f-450c-a8e5-52ae4400fb4e": {
                            "requests": 7446,
                            "bytes_in": 37230,
                            "bytes_out": 37230,
                            "details": {
                                "POST:200": 7446
                            },
                            "latency_max": 178
                        }
                    }
                }
            ]
        }
    ]
}
```

And here is the chart we ran a load-test. The app scaled up, however, just a single pod kept receiving requests.

<img width="1164" alt="Screen Shot 2022-11-11 at 10 36 03" src="https://user-images.githubusercontent.com/17990126/201351434-3dd9bdab-eab0-4666-b0d0-a5841f609927.png">

**Comment by grs** [comment]
How are you expoosing the service? It looks like it is using the service name rather than the set of pods, so there would be no loadbalancing. There is one pod target but it doesn't seem to be either of those in your graph.

What does the skupper-services configmap look like at the site where your pods are running?

**Comment by grs** [comment]
The current design is that when you expose a service, requests will just be forwarded to that service. If you expose a deployment (or a statefulset) then skupper will track the pods and balance the requests between them.

As you say, at present skupper is mostly designed to work within a namespace so you can't (at present) track pods outside the namespace skupper is running in.

**Comment by iagodvsantos** [comment]
I see! Thanks for the explanation and support.

Do you see it as a issue to keep track of the pods exposed by a service cross namespace when we use http2 protocol? 

I am saying because we might submit a PR as it would be important for us in the current skupper implementation we are doing

**Comment by grs** [comment]
I think the distinction between forwarding to pods and forwarding to a service (essentially just a name) is useful. So my initial inclination would be to allow a deployment (or statefulset) in another namespace to be exposed, rather than changing how exposing a service works. Does that make sense?

**Comment by iagodvsantos** [comment]
Indeed, it makes more sense
