### ISSUE TITLE
Transport Version mismatch -- upgrade plan

### ISSUE THREAD

**Issue by awm-rdo** [skupperproject/skupper#958]
We noticed that we could not connect clusters when there was a transport version mismatch shown when we ran the _skupper network status_ command. What is the recommended way to upgrade the versions?

=============
In the example below running skupper network status on two clusters, version 2.0.2 is from our main cluster and version 2.1.0 from a new cluster

**MAIN CLUSTER:**
Loading just local information:
 It is connected to 5 other sites (1 indirectly). Number of exposed services: 2
Sites:
╰─ [local] d8a159c - test-site.defaut
   mode: interior
   name: test-site.defaut
   namespace: default
   **version: quay.io/skupper/skupper-router:2.0.2 (sha256:0e3dc564cb16)**

-----
**NEW CLUSTER:**
Loading just local information:
 It is connected to 5 other sites (1 indirectly). Number of exposed services: 1
Sites:
╰─ [local] 6acb1d3 - new-cluster.default
   mode: interior
   name: new-cluster.default
   namespace: default
   **version: quay.io/skupper/skupper-router:2.1.0 (sha256:0e3887c570cf)**

When there's a mismatch, we get the following error message when we curl the service from our main cluster

curl -k https://new-cluster-kube-api.default.svc.cluster.local
 -> curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to new-cluster-Kube-api.default.svc.cluster.local:443

**Comment by grs** [comment]
The cluster above are connected. The error seems to be when trying to use a particular service? You can run `skupper service status` to get some more information about that, or for further debug info, `skupper debug service <servicename>`.

To update a site, if you used the cli to init in the first place you can run `skupper update` using the version of the cli that you want to upgrade to. That will set the image tag for the router accordingly and make any other necessary changes.

If using the site-controller, then just update the deployment for that to the version required. (Not that this only works if you use a more recent version that the existing one).

**Comment by awm-achi** [comment]
They are connected, but all of the connected services exhibit the same error, so I don't think it's a individual service issue. That paired with the fact that the problem is fixed when we downgraded the installation to match the skupper router version of the cluster it was trying to connect to leads us to believe it's an incompatibility between 2 skupper router versions. We understand how to upgrade a site, but we can't think of an upgrade plan that can happen without upgrading every cluster at the same exact time, since it seems like skupper isn't backwards compatible. Any guidance on how to get different versions of skupper to work together would be helpful.

**Comment by grs** [comment]
Skupper should be backwards compatible, particularly for the data plane. What does `skupper debug service` show for any of the broken services?

Also try running `kubectl exec -it <skupper-router-pod-name> -- skstat -l` at both sites.

**Comment by grs** [comment]
There was a bug in the 2.1.0 router that we believe may have caused this. That is fixed in 1.2.1, so if you upgrade the 2.1.0 site to 2.1.1 it should then be able to connect fine with 2.0.2 sites.

**Comment by awm-rdo** [comment]
Thanks for the update. We will test it.

**Comment by ted-ross** [comment]
To be clear, you should be able to upgrade successfully from 2.0.2 to 2.1.1
as well (i.e. 2.1.1 and 2.0.2 should coexist in a network without loss of
communication).

-Ted

**Comment by awm-rdo** [comment]
Following up here. We updated the client to the latest 1.3.0 and there was backward compatibility to transport version 2.0.2. Thanks!
