### ISSUE TITLE
you cannot update a site using a build of skupper

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper#982]
If you build the skupper cmd from source, a hash is used instead of a version.

If you try to update a site, you get a message like:

```
$ skupper update
Error: Site (1.2.0) is newer than library (0fe3e54); cannot update
```

**Comment by ssorj** [comment]
A scenario for this: I want to test upgrade from the current released version to the latest nightly.

**Comment by grs** [comment]
The version is deduced from the last tag on the branch in use. We tag releases on the release branches, so master has no tags. If the version is not numeric, we can't determine its relation to a specified numeric version.

You can override the default version by compiling with `make VERSION=<desired-string>`.
